// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: entity_profile_field.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MelandGame3 {

  /// <summary>Holder for reflection information generated from entity_profile_field.proto</summary>
  public static partial class EntityProfileFieldReflection {

    #region Descriptor
    /// <summary>File descriptor for entity_profile_field.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EntityProfileFieldReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChplbnRpdHlfcHJvZmlsZV9maWVsZC5wcm90bxILTWVsYW5kR2FtZTMiOwoO",
            "RW50aXR5R3VpZGFuY2USEQoJbmVlZF9zaG93GAEgASgIEhYKDmd1aWRhbmNl",
            "X2luZGV4GAIgASgJIooBCgpNZW1iZXJEYXRhEjAKCGZpZWxkX2lkGAEgASgO",
            "Mh4uTWVsYW5kR2FtZTMuRW50aXR5TWVtYmVyRmllbGQSDQoFdmFsdWUYAiAB",
            "KAUSCwoDc3RyGAMgASgJEgwKBGZsYWcYBCABKAgSDwoHaW50X2FychgFIAMo",
            "BRIPCgdzdHJfYXJyGAYgAygJKvoCChtFbnRpdHlQcm9maWxlVXBkYXRlVHJp",
            "Z2dlcnMSQgo+RW50aXR5UHJvZmlsZVVwZGF0ZVRyaWdnZXJzX0VudGl0eVBy",
            "b2ZpbGVVcGRhdGVUcmlnZ2Vyc1VuS25vd24QABJDCj9FbnRpdHlQcm9maWxl",
            "VXBkYXRlVHJpZ2dlcnNfRW50aXR5UHJvZmlsZVVwZGF0ZVRyaWdnZXJzQmVB",
            "dHRhY2sQARJHCkNFbnRpdHlQcm9maWxlVXBkYXRlVHJpZ2dlcnNfRW50aXR5",
            "UHJvZmlsZVVwZGF0ZVRyaWdnZXJzVXNDb25zdW1hYmxlEAISSApERW50aXR5",
            "UHJvZmlsZVVwZGF0ZVRyaWdnZXJzX0VudGl0eVByb2ZpbGVVcGRhdGVUcmln",
            "Z2Vyc0F1dG9SZWNvdmVySHAQAxI/CjtFbnRpdHlQcm9maWxlVXBkYXRlVHJp",
            "Z2dlcnNfRW50aXR5UHJvZmlsZVVwZGF0ZVRyaWdnZXJzQnVmZhAEKuIGChJF",
            "bnRpdHlQcm9maWxlRmllbGQSMAosRW50aXR5UHJvZmlsZUZpZWxkX0VudGl0",
            "eVByb2ZpbGVGaWVsZFVuS25vd24QABIrCidFbnRpdHlQcm9maWxlRmllbGRf",
            "RW50aXR5UHJvZmlsZUZpZWxkTHYQARIsCihFbnRpdHlQcm9maWxlRmllbGRf",
            "RW50aXR5UHJvZmlsZUZpZWxkRXhwEAISLAooRW50aXR5UHJvZmlsZUZpZWxk",
            "X0VudGl0eVByb2ZpbGVGaWVsZEF0dBADEjEKLUVudGl0eVByb2ZpbGVGaWVs",
            "ZF9FbnRpdHlQcm9maWxlRmllbGRBdHRTcGVlZBAEEiwKKEVudGl0eVByb2Zp",
            "bGVGaWVsZF9FbnRpdHlQcm9maWxlRmllbGREZWYQBRIwCixFbnRpdHlQcm9m",
            "aWxlRmllbGRfRW50aXR5UHJvZmlsZUZpZWxkSHBMaW1pdBAGEjEKLUVudGl0",
            "eVByb2ZpbGVGaWVsZF9FbnRpdHlQcm9maWxlRmllbGRDcml0UmF0ZRAHEjMK",
            "L0VudGl0eVByb2ZpbGVGaWVsZF9FbnRpdHlQcm9maWxlRmllbGRDcml0RGFt",
            "YWdlEAgSMAosRW50aXR5UHJvZmlsZUZpZWxkX0VudGl0eVByb2ZpbGVGaWVs",
            "ZEhpdFJhdGUQCRIxCi1FbnRpdHlQcm9maWxlRmllbGRfRW50aXR5UHJvZmls",
            "ZUZpZWxkTWlzc1JhdGUQChIyCi5FbnRpdHlQcm9maWxlRmllbGRfRW50aXR5",
            "UHJvZmlsZUZpZWxkTW92ZVNwZWVkEAsSMAosRW50aXR5UHJvZmlsZUZpZWxk",
            "X0VudGl0eVByb2ZpbGVGaWVsZFB1c2hEbWcQDBIxCi1FbnRpdHlQcm9maWxl",
            "RmllbGRfRW50aXR5UHJvZmlsZUZpZWxkUHVzaERpc3QQDRIyCi5FbnRpdHlQ",
            "cm9maWxlRmllbGRfRW50aXR5UHJvZmlsZUZpZWxkSHBDdXJyZW50EA4SLwor",
            "RW50aXR5UHJvZmlsZUZpZWxkX0VudGl0eVByb2ZpbGVGaWVsZFJlbmFtZRAP",
            "EjMKL0VudGl0eVByb2ZpbGVGaWVsZF9FbnRpdHlQcm9maWxlRmllbGRIcFJl",
            "Y292ZXJ5EBAq3AQKEUVudGl0eU1lbWJlckZpZWxkEiwKKEVudGl0eU1lbWJl",
            "ckZpZWxkX0VudGl0eU1lbWJlckZpZWxkRnJhbWUQABIvCitFbnRpdHlNZW1i",
            "ZXJGaWVsZF9FbnRpdHlNZW1iZXJGaWVsZFN0YW1wZWRlEAESLQopRW50aXR5",
            "TWVtYmVyRmllbGRfRW50aXR5TWVtYmVyRmllbGRMb2NrZXIQAxItCilFbnRp",
            "dHlNZW1iZXJGaWVsZF9FbnRpdHlNZW1iZXJGaWVsZElzSGlkZRAEEjEKLUVu",
            "dGl0eU1lbWJlckZpZWxkX0VudGl0eU1lbWJlckZpZWxkQ2FuRGVzdHJveRAG",
            "Ei8KK0VudGl0eU1lbWJlckZpZWxkX0VudGl0eU1lbWJlckZpZWxkR3VpZGFu",
            "Y2UQBxIuCipFbnRpdHlNZW1iZXJGaWVsZF9FbnRpdHlNZW1iZXJGaWVsZEdv",
            "ZFZpZXcQCBIuCipFbnRpdHlNZW1iZXJGaWVsZF9FbnRpdHlNZW1iZXJGaWVs",
            "ZFdhbGtEaXIQCRIvCitFbnRpdHlNZW1iZXJGaWVsZF9FbnRpdHlNZW1iZXJG",
            "aWVsZEtleXByZXNzEAoSLworRW50aXR5TWVtYmVyRmllbGRfRW50aXR5TWVt",
            "YmVyRmllbGRQbGF5QW5pbRALEjIKLkVudGl0eU1lbWJlckZpZWxkX0VudGl0",
            "eU1lbWJlckZpZWxkU2NlbmVFZmZlY3QQDBIwCixFbnRpdHlNZW1iZXJGaWVs",
            "ZF9FbnRpdHlNZW1iZXJGaWVsZFBsYXlFbW9qaRANYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::MelandGame3.EntityProfileUpdateTriggers), typeof(global::MelandGame3.EntityProfileField), typeof(global::MelandGame3.EntityMemberField), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::MelandGame3.EntityGuidance), global::MelandGame3.EntityGuidance.Parser, new[]{ "NeedShow", "GuidanceIndex" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::MelandGame3.MemberData), global::MelandGame3.MemberData.Parser, new[]{ "FieldId", "Value", "Str", "Flag", "IntArr", "StrArr" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum EntityProfileUpdateTriggers {
    [pbr::OriginalName("EntityProfileUpdateTriggers_EntityProfileUpdateTriggersUnKnown")] EntityProfileUpdateTriggersUnKnown = 0,
    [pbr::OriginalName("EntityProfileUpdateTriggers_EntityProfileUpdateTriggersBeAttack")] EntityProfileUpdateTriggersBeAttack = 1,
    [pbr::OriginalName("EntityProfileUpdateTriggers_EntityProfileUpdateTriggersUsConsumable")] EntityProfileUpdateTriggersUsConsumable = 2,
    [pbr::OriginalName("EntityProfileUpdateTriggers_EntityProfileUpdateTriggersAutoRecoverHp")] EntityProfileUpdateTriggersAutoRecoverHp = 3,
    [pbr::OriginalName("EntityProfileUpdateTriggers_EntityProfileUpdateTriggersBuff")] EntityProfileUpdateTriggersBuff = 4,
  }

  public enum EntityProfileField {
    [pbr::OriginalName("EntityProfileField_EntityProfileFieldUnKnown")] EntityProfileFieldUnKnown = 0,
    [pbr::OriginalName("EntityProfileField_EntityProfileFieldLv")] EntityProfileFieldLv = 1,
    [pbr::OriginalName("EntityProfileField_EntityProfileFieldExp")] EntityProfileFieldExp = 2,
    [pbr::OriginalName("EntityProfileField_EntityProfileFieldAtt")] EntityProfileFieldAtt = 3,
    [pbr::OriginalName("EntityProfileField_EntityProfileFieldAttSpeed")] EntityProfileFieldAttSpeed = 4,
    [pbr::OriginalName("EntityProfileField_EntityProfileFieldDef")] EntityProfileFieldDef = 5,
    [pbr::OriginalName("EntityProfileField_EntityProfileFieldHpLimit")] EntityProfileFieldHpLimit = 6,
    [pbr::OriginalName("EntityProfileField_EntityProfileFieldCritRate")] EntityProfileFieldCritRate = 7,
    [pbr::OriginalName("EntityProfileField_EntityProfileFieldCritDamage")] EntityProfileFieldCritDamage = 8,
    [pbr::OriginalName("EntityProfileField_EntityProfileFieldHitRate")] EntityProfileFieldHitRate = 9,
    [pbr::OriginalName("EntityProfileField_EntityProfileFieldMissRate")] EntityProfileFieldMissRate = 10,
    [pbr::OriginalName("EntityProfileField_EntityProfileFieldMoveSpeed")] EntityProfileFieldMoveSpeed = 11,
    [pbr::OriginalName("EntityProfileField_EntityProfileFieldPushDmg")] EntityProfileFieldPushDmg = 12,
    [pbr::OriginalName("EntityProfileField_EntityProfileFieldPushDist")] EntityProfileFieldPushDist = 13,
    [pbr::OriginalName("EntityProfileField_EntityProfileFieldHpCurrent")] EntityProfileFieldHpCurrent = 14,
    [pbr::OriginalName("EntityProfileField_EntityProfileFieldRename")] EntityProfileFieldRename = 15,
    [pbr::OriginalName("EntityProfileField_EntityProfileFieldHpRecovery")] EntityProfileFieldHpRecovery = 16,
  }

  public enum EntityMemberField {
    /// <summary>
    ///帧数(pram int32)
    /// </summary>
    [pbr::OriginalName("EntityMemberField_EntityMemberFieldFrame")] EntityMemberFieldFrame = 0,
    /// <summary>
    ///踩踏状态(pram bool)
    /// </summary>
    [pbr::OriginalName("EntityMemberField_EntityMemberFieldStampede")] EntityMemberFieldStampede = 1,
    /// <summary>
    ///被谁锁(pram string)
    /// </summary>
    [pbr::OriginalName("EntityMemberField_EntityMemberFieldLocker")] EntityMemberFieldLocker = 3,
    /// <summary>
    ///是否已隐藏(pram bool)
    /// </summary>
    [pbr::OriginalName("EntityMemberField_EntityMemberFieldIsHide")] EntityMemberFieldIsHide = 4,
    /// <summary>
    ///是否可以摧毁 (pram bool)
    /// </summary>
    [pbr::OriginalName("EntityMemberField_EntityMemberFieldCanDestroy")] EntityMemberFieldCanDestroy = 6,
    /// <summary>
    ///引导提示信息 (pram bool + string)
    /// </summary>
    [pbr::OriginalName("EntityMemberField_EntityMemberFieldGuidance")] EntityMemberFieldGuidance = 7,
    /// <summary>
    ///上帝视角
    /// </summary>
    [pbr::OriginalName("EntityMemberField_EntityMemberFieldGodView")] EntityMemberFieldGodView = 8,
    /// <summary>
    ///通行方向
    /// </summary>
    [pbr::OriginalName("EntityMemberField_EntityMemberFieldWalkDir")] EntityMemberFieldWalkDir = 9,
    /// <summary>
    ///键盘输入的按键(pram str_arr)
    /// </summary>
    [pbr::OriginalName("EntityMemberField_EntityMemberFieldKeypress")] EntityMemberFieldKeypress = 10,
    /// <summary>
    ///当前播放的动画(pram int32)
    /// </summary>
    [pbr::OriginalName("EntityMemberField_EntityMemberFieldPlayAnim")] EntityMemberFieldPlayAnim = 11,
    /// <summary>
    ///当前使用场景效果(pram int32)\
    /// </summary>
    [pbr::OriginalName("EntityMemberField_EntityMemberFieldSceneEffect")] EntityMemberFieldSceneEffect = 12,
    /// <summary>
    ///当前播放的表情(pram int32)
    /// </summary>
    [pbr::OriginalName("EntityMemberField_EntityMemberFieldPlayEmoji")] EntityMemberFieldPlayEmoji = 13,
  }

  #endregion

  #region Messages
  public sealed partial class EntityGuidance : pb::IMessage<EntityGuidance>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EntityGuidance> _parser = new pb::MessageParser<EntityGuidance>(() => new EntityGuidance());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<EntityGuidance> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MelandGame3.EntityProfileFieldReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EntityGuidance() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EntityGuidance(EntityGuidance other) : this() {
      needShow_ = other.needShow_;
      guidanceIndex_ = other.guidanceIndex_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EntityGuidance Clone() {
      return new EntityGuidance(this);
    }

    /// <summary>Field number for the "need_show" field.</summary>
    public const int NeedShowFieldNumber = 1;
    private bool needShow_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool NeedShow {
      get { return needShow_; }
      set {
        needShow_ = value;
      }
    }

    /// <summary>Field number for the "guidance_index" field.</summary>
    public const int GuidanceIndexFieldNumber = 2;
    private string guidanceIndex_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string GuidanceIndex {
      get { return guidanceIndex_; }
      set {
        guidanceIndex_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as EntityGuidance);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(EntityGuidance other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (NeedShow != other.NeedShow) return false;
      if (GuidanceIndex != other.GuidanceIndex) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (NeedShow != false) hash ^= NeedShow.GetHashCode();
      if (GuidanceIndex.Length != 0) hash ^= GuidanceIndex.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (NeedShow != false) {
        output.WriteRawTag(8);
        output.WriteBool(NeedShow);
      }
      if (GuidanceIndex.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(GuidanceIndex);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (NeedShow != false) {
        output.WriteRawTag(8);
        output.WriteBool(NeedShow);
      }
      if (GuidanceIndex.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(GuidanceIndex);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (NeedShow != false) {
        size += 1 + 1;
      }
      if (GuidanceIndex.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(GuidanceIndex);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(EntityGuidance other) {
      if (other == null) {
        return;
      }
      if (other.NeedShow != false) {
        NeedShow = other.NeedShow;
      }
      if (other.GuidanceIndex.Length != 0) {
        GuidanceIndex = other.GuidanceIndex;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            NeedShow = input.ReadBool();
            break;
          }
          case 18: {
            GuidanceIndex = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            NeedShow = input.ReadBool();
            break;
          }
          case 18: {
            GuidanceIndex = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class MemberData : pb::IMessage<MemberData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MemberData> _parser = new pb::MessageParser<MemberData>(() => new MemberData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MemberData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MelandGame3.EntityProfileFieldReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MemberData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MemberData(MemberData other) : this() {
      fieldId_ = other.fieldId_;
      value_ = other.value_;
      str_ = other.str_;
      flag_ = other.flag_;
      intArr_ = other.intArr_.Clone();
      strArr_ = other.strArr_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MemberData Clone() {
      return new MemberData(this);
    }

    /// <summary>Field number for the "field_id" field.</summary>
    public const int FieldIdFieldNumber = 1;
    private global::MelandGame3.EntityMemberField fieldId_ = global::MelandGame3.EntityMemberField.EntityMemberFieldFrame;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::MelandGame3.EntityMemberField FieldId {
      get { return fieldId_; }
      set {
        fieldId_ = value;
      }
    }

    /// <summary>Field number for the "value" field.</summary>
    public const int ValueFieldNumber = 2;
    private int value_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Value {
      get { return value_; }
      set {
        value_ = value;
      }
    }

    /// <summary>Field number for the "str" field.</summary>
    public const int StrFieldNumber = 3;
    private string str_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Str {
      get { return str_; }
      set {
        str_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "flag" field.</summary>
    public const int FlagFieldNumber = 4;
    private bool flag_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Flag {
      get { return flag_; }
      set {
        flag_ = value;
      }
    }

    /// <summary>Field number for the "int_arr" field.</summary>
    public const int IntArrFieldNumber = 5;
    private static readonly pb::FieldCodec<int> _repeated_intArr_codec
        = pb::FieldCodec.ForInt32(42);
    private readonly pbc::RepeatedField<int> intArr_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> IntArr {
      get { return intArr_; }
    }

    /// <summary>Field number for the "str_arr" field.</summary>
    public const int StrArrFieldNumber = 6;
    private static readonly pb::FieldCodec<string> _repeated_strArr_codec
        = pb::FieldCodec.ForString(50);
    private readonly pbc::RepeatedField<string> strArr_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> StrArr {
      get { return strArr_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MemberData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MemberData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (FieldId != other.FieldId) return false;
      if (Value != other.Value) return false;
      if (Str != other.Str) return false;
      if (Flag != other.Flag) return false;
      if(!intArr_.Equals(other.intArr_)) return false;
      if(!strArr_.Equals(other.strArr_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (FieldId != global::MelandGame3.EntityMemberField.EntityMemberFieldFrame) hash ^= FieldId.GetHashCode();
      if (Value != 0) hash ^= Value.GetHashCode();
      if (Str.Length != 0) hash ^= Str.GetHashCode();
      if (Flag != false) hash ^= Flag.GetHashCode();
      hash ^= intArr_.GetHashCode();
      hash ^= strArr_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (FieldId != global::MelandGame3.EntityMemberField.EntityMemberFieldFrame) {
        output.WriteRawTag(8);
        output.WriteEnum((int) FieldId);
      }
      if (Value != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Value);
      }
      if (Str.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Str);
      }
      if (Flag != false) {
        output.WriteRawTag(32);
        output.WriteBool(Flag);
      }
      intArr_.WriteTo(output, _repeated_intArr_codec);
      strArr_.WriteTo(output, _repeated_strArr_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (FieldId != global::MelandGame3.EntityMemberField.EntityMemberFieldFrame) {
        output.WriteRawTag(8);
        output.WriteEnum((int) FieldId);
      }
      if (Value != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Value);
      }
      if (Str.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Str);
      }
      if (Flag != false) {
        output.WriteRawTag(32);
        output.WriteBool(Flag);
      }
      intArr_.WriteTo(ref output, _repeated_intArr_codec);
      strArr_.WriteTo(ref output, _repeated_strArr_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (FieldId != global::MelandGame3.EntityMemberField.EntityMemberFieldFrame) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) FieldId);
      }
      if (Value != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Value);
      }
      if (Str.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Str);
      }
      if (Flag != false) {
        size += 1 + 1;
      }
      size += intArr_.CalculateSize(_repeated_intArr_codec);
      size += strArr_.CalculateSize(_repeated_strArr_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MemberData other) {
      if (other == null) {
        return;
      }
      if (other.FieldId != global::MelandGame3.EntityMemberField.EntityMemberFieldFrame) {
        FieldId = other.FieldId;
      }
      if (other.Value != 0) {
        Value = other.Value;
      }
      if (other.Str.Length != 0) {
        Str = other.Str;
      }
      if (other.Flag != false) {
        Flag = other.Flag;
      }
      intArr_.Add(other.intArr_);
      strArr_.Add(other.strArr_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            FieldId = (global::MelandGame3.EntityMemberField) input.ReadEnum();
            break;
          }
          case 16: {
            Value = input.ReadInt32();
            break;
          }
          case 26: {
            Str = input.ReadString();
            break;
          }
          case 32: {
            Flag = input.ReadBool();
            break;
          }
          case 42:
          case 40: {
            intArr_.AddEntriesFrom(input, _repeated_intArr_codec);
            break;
          }
          case 50: {
            strArr_.AddEntriesFrom(input, _repeated_strArr_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            FieldId = (global::MelandGame3.EntityMemberField) input.ReadEnum();
            break;
          }
          case 16: {
            Value = input.ReadInt32();
            break;
          }
          case 26: {
            Str = input.ReadString();
            break;
          }
          case 32: {
            Flag = input.ReadBool();
            break;
          }
          case 42:
          case 40: {
            intArr_.AddEntriesFrom(ref input, _repeated_intArr_codec);
            break;
          }
          case 50: {
            strArr_.AddEntriesFrom(ref input, _repeated_strArr_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
