// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: server_event.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MelandGame3 {

  /// <summary>Holder for reflection information generated from server_event.proto</summary>
  public static partial class ServerEventReflection {

    #region Descriptor
    /// <summary>File descriptor for server_event.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServerEventReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJzZXJ2ZXJfZXZlbnQucHJvdG8SC01lbGFuZEdhbWUzKt8BChJTZXJ2ZXJN",
            "c2dFdmVudFR5cGUSLworU2VydmVyTXNnRXZlbnRUeXBlX1NlcnZlck1zZ0V2",
            "ZW50VHlwZVVua25vdxAAEjMKL1NlcnZlck1zZ0V2ZW50VHlwZV9TZXJ2ZXJN",
            "c2dFdmVudFR5cGVSZWNlaXZlTXNnEAESMQotU2VydmVyTXNnRXZlbnRUeXBl",
            "X1NlcnZlck1zZ0V2ZW50VHlwZUNhbGxCYWNrEAISMAosU2VydmVyTXNnRXZl",
            "bnRUeXBlX1NlcnZlck1zZ0V2ZW50VHlwZVRpbWVPdXQQAyqBJgoPU2VydmVy",
            "RXZlbnRUeXBlEjAKLFNlcnZlckV2ZW50VHlwZV9TZXJ2ZXJFdmVudFR5cGVT",
            "ZXJ2ZXJVbmtub3duEAASNAowU2VydmVyRXZlbnRUeXBlX1NlcnZlckV2ZW50",
            "VHlwZVNlcnZlckFmdGVyQ29uZmlnEAoSMQotU2VydmVyRXZlbnRUeXBlX1Nl",
            "cnZlckV2ZW50VHlwZVNlcnZlck1pbnV0ZWx5EAsSLworU2VydmVyRXZlbnRU",
            "eXBlX1NlcnZlckV2ZW50VHlwZVNlcnZlckhvdXJseRAMEi4KKlNlcnZlckV2",
            "ZW50VHlwZV9TZXJ2ZXJFdmVudFR5cGVTZXJ2ZXJEYWlseRANEjIKLlNlcnZl",
            "ckV2ZW50VHlwZV9TZXJ2ZXJFdmVudFR5cGVTZXJ2ZXJDb25uQ2xvc2UQDhI0",
            "CjBTZXJ2ZXJFdmVudFR5cGVfU2VydmVyRXZlbnRUeXBlU2VydmVyQ29ubkNv",
            "bm5lY3QQDxIuCipTZXJ2ZXJFdmVudFR5cGVfU2VydmVyRXZlbnRUeXBlU2Vy",
            "dmVyVGltZXIQEBIuCipTZXJ2ZXJFdmVudFR5cGVfU2VydmVyRXZlbnRUeXBl",
            "U3FsUm9sbEJhY2sQERIyCi5TZXJ2ZXJFdmVudFR5cGVfU2VydmVyRXZlbnRU",
            "eXBlU2VydmVyRXZlbnRDYWxsEBISMAosU2VydmVyRXZlbnRUeXBlX1NlcnZl",
            "ckV2ZW50VHlwZVBsYXllckNyZWF0ZWQQZBIvCitTZXJ2ZXJFdmVudFR5cGVf",
            "U2VydmVyRXZlbnRUeXBlUGxheWVyT25saW5lEGUSMAosU2VydmVyRXZlbnRU",
            "eXBlX1NlcnZlckV2ZW50VHlwZVBsYXllck9mZmxpbmUQZhIvCitTZXJ2ZXJF",
            "dmVudFR5cGVfU2VydmVyRXZlbnRUeXBlUGxheWVyTmV3RGF5EGcSLQopU2Vy",
            "dmVyRXZlbnRUeXBlX1NlcnZlckV2ZW50VHlwZVBsYXllckx2VXAQaBI1CjFT",
            "ZXJ2ZXJFdmVudFR5cGVfU2VydmVyRXZlbnRUeXBlUGxheWVyUmVzZXRQcm9m",
            "aWxlEGkSNAowU2VydmVyRXZlbnRUeXBlX1NlcnZlckV2ZW50VHlwZVBsYXll",
            "clVwZGF0ZVNraWxsEGoSLworU2VydmVyRXZlbnRUeXBlX1NlcnZlckV2ZW50",
            "VHlwZVBsYXllckFkZEV4cBBrEjIKLlNlcnZlckV2ZW50VHlwZV9TZXJ2ZXJF",
            "dmVudFR5cGVQbGF5ZXJEZWR1Y3RFeHAQbBIwCixTZXJ2ZXJFdmVudFR5cGVf",
            "U2VydmVyRXZlbnRUeXBlUGxheWVyUmVwbHlIcBBtEjkKNVNlcnZlckV2ZW50",
            "VHlwZV9TZXJ2ZXJFdmVudFR5cGVDYWxjdWxhdGVQbGF5ZXJQcm9maWxlEG4S",
            "MQotU2VydmVyRXZlbnRUeXBlX1NlcnZlckV2ZW50VHlwZVBsYXllclVzZVNr",
            "aWxsEG8SMQotU2VydmVyRXZlbnRUeXBlX1NlcnZlckV2ZW50VHlwZVBsYXll",
            "ckJlQXR0YWNrEHASLgoqU2VydmVyRXZlbnRUeXBlX1NlcnZlckV2ZW50VHlw",
            "ZURlc3RvcnlJdGVtEHISMQotU2VydmVyRXZlbnRUeXBlX1NlcnZlckV2ZW50",
            "VHlwZURlc3RvcnlBbGxJdGVtEHMSKgomU2VydmVyRXZlbnRUeXBlX1NlcnZl",
            "ckV2ZW50VHlwZUFkZEl0ZW0QdBIuCipTZXJ2ZXJFdmVudFR5cGVfU2VydmVy",
            "RXZlbnRUeXBlUmVkZWVtQ0RLZXkQdRIqCiZTZXJ2ZXJFdmVudFR5cGVfU2Vy",
            "dmVyRXZlbnRUeXBlRHVuZ2VvbhB2Ei4KKlNlcnZlckV2ZW50VHlwZV9TZXJ2",
            "ZXJFdmVudFR5cGVTZW5kQ2hhdE1zZxB3EjYKMlNlcnZlckV2ZW50VHlwZV9T",
            "ZXJ2ZXJFdmVudFR5cGVTZW5kVXBkYXRlQ2hhdFN0YXRlEHgSNAowU2VydmVy",
            "RXZlbnRUeXBlX1NlcnZlckV2ZW50VHlwZVNlbmRSZW1vdmVDaGF0TXNnEHkS",
            "MAorU2VydmVyRXZlbnRUeXBlX1NlcnZlckV2ZW50Wm9uZVNlbmRUb1BsYXll",
            "chDIARIlCiBTZXJ2ZXJFdmVudFR5cGVfWjJTWm9uZUJyb2FkY2FzdBDKARI1",
            "CjBTZXJ2ZXJFdmVudFR5cGVfU2VydmVyRXZlbnRFbnRpdHlBbmltYXRpb25D",
            "cmVhdGUQywESNQowU2VydmVyRXZlbnRUeXBlX1NlcnZlckV2ZW50RW50aXR5",
            "QW5pbWF0aW9uVXBkYXRlEMwBEjIKLVNlcnZlckV2ZW50VHlwZV9TZXJ2ZXJF",
            "dmVudEVudGl0eUFuaW1hdGlvbkRlbBDNARIiCh1TZXJ2ZXJFdmVudFR5cGVf",
            "WjJTR29iTWFwU2F2ZRDOARIyCi1TZXJ2ZXJFdmVudFR5cGVfU2VydmVyRXZl",
            "bnRFbnRpdHlQbGF5ZXJVcGRhdGUQzwESKgolU2VydmVyRXZlbnRUeXBlX1oy",
            "U0VudGl0eVRlbXBsYXRlU2F2ZRDQARIlCiBTZXJ2ZXJFdmVudFR5cGVfWjJT",
            "UGxheWVyT2ZmbGluZRDSARInCiJTZXJ2ZXJFdmVudFR5cGVfWjJTUGxheWVy",
            "TWFub3JEYXRhENMBEioKJVNlcnZlckV2ZW50VHlwZV9TZXJ2ZXJFdmVudEVu",
            "dGl0eVNhdmUQ1QESIwoeU2VydmVyRXZlbnRUeXBlX1oyU0J1aWxkRGVsZXRl",
            "EPIBEiUKIFNlcnZlckV2ZW50VHlwZV9TZXJ2ZXJFdmVudEJ1aWxkEPMBEiQK",
            "H1NlcnZlckV2ZW50VHlwZV9aMlNQdXBwZXREZWxldGUQ9AESIgodU2VydmVy",
            "RXZlbnRUeXBlX1oyU1BsYXllclNhdmUQjwMSIgodU2VydmVyRXZlbnRUeXBl",
            "X1oyU0VudGl0eVNhdmUQkAMSIwoeU2VydmVyRXZlbnRUeXBlX1oyU01hbm9y",
            "UGFja2V0EJEDEisKJlNlcnZlckV2ZW50VHlwZV9TZXJ2ZXJFdmVudENvZGVF",
            "eGVjdXRlEPQDEi8KKlNlcnZlckV2ZW50VHlwZV9TZXJ2ZXJFdmVudFVzZUl0",
            "ZW1Gcm9tWm9uZRD1AxIwCitTZXJ2ZXJFdmVudFR5cGVfU2VydmVyRXZlbnRE",
            "cm9wSXRlbUZyb21ab25lEPYDEjAKK1NlcnZlckV2ZW50VHlwZV9TZXJ2ZXJF",
            "dmVudEJvdEJ1aWxkRnJvbVpvbmUQ9wMSMAorU2VydmVyRXZlbnRUeXBlX1Nl",
            "cnZlckV2ZW50TWFrZUl0ZW1Gcm9tWm9uZRD5AxI+CjlTZXJ2ZXJFdmVudFR5",
            "cGVfU2VydmVyRXZlbnRUYWtlV29ya2JlbmNoSXRlbUJ5Q2lkRnJvbVpvbmUQ",
            "+gMSPgo5U2VydmVyRXZlbnRUeXBlX1NlcnZlckV2ZW50R2l2ZVdvcmtiZW5j",
            "aEl0ZW1CeUNpZEZyb21ab25lEPsDEjUKMFNlcnZlckV2ZW50VHlwZV9TZXJ2",
            "ZXJFdmVudFBsYXllckNvbXBsZXRlQ2hhcHRlchD8AxIsCidTZXJ2ZXJFdmVu",
            "dFR5cGVfU2VydmVyRXZlbnRNaXNzaW9uRW50ZXIQ/QMSKgolU2VydmVyRXZl",
            "bnRUeXBlX1NlcnZlckV2ZW50QWNjZXB0VGFzaxD+AxIqCiVTZXJ2ZXJFdmVu",
            "dFR5cGVfU2VydmVyRXZlbnRTdWJtaXRUYXNrEP8DEiwKJ1NlcnZlckV2ZW50",
            "VHlwZV9TZXJ2ZXJFdmVudENvbXBsYXRlVGFzaxCABBI4CjNTZXJ2ZXJFdmVu",
            "dFR5cGVfU2VydmVyRXZlbnRNaXNzaW9uRW50ZXJTY2VuZU1vbml0b3IQgQQS",
            "IwoeU2VydmVyRXZlbnRUeXBlX1oyU19QbGF5ZXJEZWFkEMgFEi4KKVNlcnZl",
            "ckV2ZW50VHlwZV9TZXJ2ZXJFdmVudFoyU0FkZEV4cFRvQm90EMsFEioKJVNl",
            "cnZlckV2ZW50VHlwZV9TZXJ2ZXJFdmVudFoyU0JvdERlYWQQ2wUSIwoeU2Vy",
            "dmVyRXZlbnRUeXBlX1oyU1BsYW50RGVsZXRlEPEFEiEKHFNlcnZlckV2ZW50",
            "VHlwZV9aMlNQZXREZWxldGUQ8gUSLgopU2VydmVyRXZlbnRUeXBlX1NlcnZl",
            "ckV2ZW50VHlwZUJvdENyZWF0ZWQQoAYSKwomU2VydmVyRXZlbnRUeXBlX1Nl",
            "cnZlckV2ZW50VHlwZUJvdEx2VXAQoQYSNgoxU2VydmVyRXZlbnRUeXBlX1Nl",
            "cnZlckV2ZW50VHlwZVVwZGF0ZUJvdEVxdWlwbWVudBCiBhItCihTZXJ2ZXJF",
            "dmVudFR5cGVfU2VydmVyRXZlbnRUeXBlQm90QWRkRXhwEKMGEi4KKVNlcnZl",
            "ckV2ZW50VHlwZV9TZXJ2ZXJFdmVudFR5cGVCb3RSZXBseUhwEKQGEjAKK1Nl",
            "cnZlckV2ZW50VHlwZV9TZXJ2ZXJFdmVudFR5cGVCb3RBZGRPYmplY3QQpQYS",
            "LQooU2VydmVyRXZlbnRUeXBlX1NlcnZlckV2ZW50VHlwZVJlY2FsbEJvdBCm",
            "BhIvCipTZXJ2ZXJFdmVudFR5cGVfU2VydmVyRXZlbnRUeXBlQm90VXNlU2tp",
            "bGwQpwYSLwoqU2VydmVyRXZlbnRUeXBlX1NlcnZlckV2ZW50VHlwZUJvdEJl",
            "QXR0YWNrEKgGEi4KKVNlcnZlckV2ZW50VHlwZV9TZXJ2ZXJFdmVudFR5cGVC",
            "b3RBZGRJdGVtEKkGEjcKMlNlcnZlckV2ZW50VHlwZV9TZXJ2ZXJFdmVudFR5",
            "cGVQbGF5ZXJVc2VDb25zdW1hYmxlEIYHEjMKLlNlcnZlckV2ZW50VHlwZV9T",
            "ZXJ2ZXJFdmVudFR5cGVQbGF5ZXJBZGRPYmplY3QQhwcSIwoeU2VydmVyRXZl",
            "bnRUeXBlX1oyU1BpY2tGYWxsaW5nEIgHEiYKIVNlcnZlckV2ZW50VHlwZV9a",
            "MlNQaWNrRmFsbGluZ0JveBCJBxIzCi5TZXJ2ZXJFdmVudFR5cGVfU2VydmVy",
            "RXZlbnRUeXBlUGxheWVyVXNlT2JqZWN0EIsHEjoKNVNlcnZlckV2ZW50VHlw",
            "ZV9TZXJ2ZXJFdmVudFR5cGVBZGRJdGVtQnlPcGVyYXRlQnViYmxlEIwHEjsK",
            "NlNlcnZlckV2ZW50VHlwZV9TZXJ2ZXJFdmVudFR5cGVUYWtlSXRlbUJ5T3Bl",
            "cmF0ZUJ1YmJsZRCNBxI+CjlTZXJ2ZXJFdmVudFR5cGVfU2VydmVyRXZlbnRU",
            "eXBlUmVwbGFjZUl0ZW1CeU9wZXJhdGVCdWJibGUQjgcSOAozU2VydmVyRXZl",
            "bnRUeXBlX1NlcnZlckV2ZW50VHlwZVJlc2V0UGxheWVyTmZ0U3RhdHVzEI8H",
            "EjQKL1NlcnZlckV2ZW50VHlwZV9TZXJ2ZXJFdmVudFR5cGVVcGRhdGVQbGF5",
            "ZXJORlRzEJAHEjkKNFNlcnZlckV2ZW50VHlwZV9TZXJ2ZXJFdmVudFR5cGVV",
            "cGRhdGVUaGlyZE5mdFRpbWVPdXQQkwcSNgoxU2VydmVyRXZlbnRUeXBlX1Nl",
            "cnZlckV2ZW50VHlwZVBsYXllckFjY2VwdGVkVGFzaxDpBxI3CjJTZXJ2ZXJF",
            "dmVudFR5cGVfU2VydmVyRXZlbnRUeXBlUGxheWVyU3VibWl0dGVkVGFzaxDq",
            "BxI7CjZTZXJ2ZXJFdmVudFR5cGVfU2VydmVyRXZlbnRUeXBlVXBkYXRlTnBj",
            "VGFza05vdGljZVR5cGUQ6wcSOQo0U2VydmVyRXZlbnRUeXBlX1NlcnZlckV2",
            "ZW50VHlwZVBsYXllclRhc2tTdGF0ZVVwZGF0ZRDtBxIyCi1TZXJ2ZXJFdmVu",
            "dFR5cGVfU2VydmVyRXZlbnRUYXNrUHJvZ3Jlc3NDaGFuZ2UQmQgSMQosU2Vy",
            "dmVyRXZlbnRUeXBlX1NlcnZlckV2ZW50VHlwZVBsYXllckFkZE1haWwQmwgS",
            "Pgo5U2VydmVyRXZlbnRUeXBlX1NlcnZlckV2ZW50VHlwZVNlcnZlclNlbmRN",
            "YWlsQnlUZW1wbGF0ZUlkEJwIEjMKLlNlcnZlckV2ZW50VHlwZV9TZXJ2ZXJF",
            "dmVudFR5cGVMYW5kR3JvdXBDcmVhdGUQqEYSMwouU2VydmVyRXZlbnRUeXBl",
            "X1NlcnZlckV2ZW50VHlwZUxhbmRHcm91cFVwZGF0ZRCpRhIzCi5TZXJ2ZXJF",
            "dmVudFR5cGVfU2VydmVyRXZlbnRUeXBlTGFuZEdyb3VwUmVtb3ZlEKpGEisK",
            "JVNlcnZlckV2ZW50VHlwZV9TZXJ2ZXJFdmVudFR5cGVOdW1NYXgQ//8DKpwl",
            "Cg5Xb3JsZEV2ZW50VHlwZRIoCiRXb3JsZEV2ZW50VHlwZV9Xb3JsZEV2ZW50",
            "VHlwZVVua25vd24QABIrCidXb3JsZEV2ZW50VHlwZV9Xb3JsZEV2ZW50VHlw",
            "ZVNlbmRUb1pvbmUQARIpCiVXb3JsZEV2ZW50VHlwZV9Xb3JsZEV2ZW50VHlw",
            "ZUVudGVyTWFwEAISKQolV29ybGRFdmVudFR5cGVfV29ybGRFdmVudFR5cGVM",
            "ZWF2ZU1hcBADEiUKIVdvcmxkRXZlbnRUeXBlX1dvcmxkRXZlbnRUeXBlTW92",
            "ZRAEEigKJFdvcmxkRXZlbnRUeXBlX1dvcmxkRXZlbnRUeXBlTWFwU2F2ZRAF",
            "EjQKMFdvcmxkRXZlbnRUeXBlX1dvcmxkRXZlbnRUeXBlUmVsb2FkUmVzb3Vy",
            "Y2VQb2ludBAGEi8KK1dvcmxkRXZlbnRUeXBlX1dvcmxkRXZlbnRUeXBlSW5p",
            "dE1hcEVsZW1lbnQQBxIrCidXb3JsZEV2ZW50VHlwZV9Xb3JsZEV2ZW50VHlw",
            "ZUVudGl0eVNhdmUQCBIsCihXb3JsZEV2ZW50VHlwZV9Xb3JsZEV2ZW50VHlw",
            "ZVBsYXllclJlc2V0EAkSLworV29ybGRFdmVudFR5cGVfV29ybGRFdmVudFR5",
            "cGVSZXNldEFyZWFTdGF0ZRAKEjMKL1dvcmxkRXZlbnRUeXBlX1dvcmxkRXZl",
            "bnRUeXBlRGl1cm5hbEN5Y2xlQ2hhbmdlEB4SMAosV29ybGRFdmVudFR5cGVf",
            "V29ybGRFdmVudFR5cGVFbnRpdHlFdmVudENhbGwQZRI1CjFXb3JsZEV2ZW50",
            "VHlwZV9Xb3JsZEV2ZW50VHlwZUFkZEVudGl0eVRvQ2h1bmtHcmlkEGYSKgom",
            "V29ybGRFdmVudFR5cGVfV29ybGRFdmVudFR5cGVHZXRFbnRpdHkQaBI4CjRX",
            "b3JsZEV2ZW50VHlwZV9Xb3JsZEV2ZW50VHlwZUVudGl0eUV2ZW50Q2FsbE5v",
            "UmV0dXJuEGkSPAo4V29ybGRFdmVudFR5cGVfV29ybGRFdmVudFR5cGVSZXN0",
            "YXJ0QWxsRW50aXRpZXNDb2RlQmxvY2sQahIzCi9Xb3JsZEV2ZW50VHlwZV9X",
            "b3JsZEV2ZW50VHlwZVJlc291cmNlTG9hZEZpbmlzaBBrEjEKLVdvcmxkRXZl",
            "bnRUeXBlX1dvcmxkRXZlbnRUeXBlVXBkYXRlV2lkZ2V0QXR0chBsEjkKNVdv",
            "cmxkRXZlbnRUeXBlX1dvcmxkRXZlbnRUeXBlUnVuQ29kZUJsb2NrQnlQbGF5",
            "ZXJBcmVhEG0SOQo1V29ybGRFdmVudFR5cGVfV29ybGRFdmVudFR5cGVFbnRp",
            "dGllc1Jlc3RhcnRDb2RlQmxvY2sQbhI2CjJXb3JsZEV2ZW50VHlwZV9Xb3Js",
            "ZEV2ZW50VHlwZVB1YmxpY0FyZWFSZXN0YXJ0Q29kZRBwEjYKMldvcmxkRXZl",
            "bnRUeXBlX1dvcmxkRXZlbnRUeXBlUGxheWVyQXJlYVJlc3RhcnRDb2RlEHES",
            "MwovV29ybGRFdmVudFR5cGVfV29ybGRFdmVudFR5cGVSZW1vdmVFbnRpdHlD",
            "aGFuZ2UQchItCilXb3JsZEV2ZW50VHlwZV9Xb3JsZEV2ZW50VHlwZVJldml2",
            "ZUVudGl0eRBzEjIKLldvcmxkRXZlbnRUeXBlX1dvcmxkRXZlbnRUeXBlUmVz",
            "dGFydER1bmdlb25NYXAQdBI6CjZXb3JsZEV2ZW50VHlwZV9Xb3JsZEV2ZW50",
            "VHlwZUVudGl0aWVzRXhlY3V0ZVN0YXJ0RXZlbnQQdRI2CjJXb3JsZEV2ZW50",
            "VHlwZV9Xb3JsZEV2ZW50VHlwZUVudGl0aWVzU3RvcENvZGVCbG9jaxB2EjQK",
            "MFdvcmxkRXZlbnRUeXBlX1dvcmxkRXZlbnRUeXBlQXBwbHlFbnRpdHlUZW1w",
            "bGF0ZRB4EjUKMVdvcmxkRXZlbnRUeXBlX1dvcmxkRXZlbnRUeXBlQWRkQ2Ft",
            "ZXJhVG9DaHVua0dyaWQQeRI0CjBXb3JsZEV2ZW50VHlwZV9Xb3JsZEV2ZW50",
            "VHlwZVpvbmVBcmVhUmVzdGFydENvZGUQehJACjxXb3JsZEV2ZW50VHlwZV9X",
            "b3JsZEV2ZW50VHlwZUFkZEVudGl0eVdpdGhvdXRWaWV3VG9DaHVua0dyaWQQ",
            "exI2CjJXb3JsZEV2ZW50VHlwZV9Xb3JsZEV2ZW50VHlwZUNvZGVFdmVudE5v",
            "dGlmaWNhdGlvbhB8EjkKNVdvcmxkRXZlbnRUeXBlX1dvcmxkRXZlbnRUeXBl",
            "UHVibGljQXJlYVJlc2V0Q29kZUJsb2NrEH0SQwo/V29ybGRFdmVudFR5cGVf",
            "V29ybGRFdmVudFR5cGVFbnRpdGllc0V4ZWN1dGVRdWlja0NvZGVTdGFydEV2",
            "ZW50EH4SPAo4V29ybGRFdmVudFR5cGVfV29ybGRFdmVudFR5cGVSZXNldEVu",
            "dGl0aWVzUXVpY2tDb2RlU3RhdGUQfxI7CjZXb3JsZEV2ZW50VHlwZV9Xb3Js",
            "ZEV2ZW50VHlwZUVudGl0aWVzUXVpY2tDb2RlVGFiRGF0YXMQgAESLQooV29y",
            "bGRFdmVudFR5cGVfV29ybGRFdmVudFR5cGVUb0dyaWRFdmVudBCWARIrCiZX",
            "b3JsZEV2ZW50VHlwZV9Xb3JsZEV2ZW50VHlwZVpvb21FdmVudBCXARIxCixX",
            "b3JsZEV2ZW50VHlwZV9Xb3JsZEV2ZW50VHlwZVBsYXllckFkZEVudGl0eRDJ",
            "ARIxCixXb3JsZEV2ZW50VHlwZV9Xb3JsZEV2ZW50VHlwZVBsYXllckRlbEVu",
            "dGl0eRDKARIyCi1Xb3JsZEV2ZW50VHlwZV9Xb3JsZEV2ZW50VHlwZVBsYXll",
            "ck1vdmVFbnRpdHkQywESLgopV29ybGRFdmVudFR5cGVfV29ybGRFdmVudFR5",
            "cGVCb3RBZGRFbnRpdHkQzAESOAozV29ybGRFdmVudFR5cGVfV29ybGRFdmVu",
            "dFR5cGVQbGF5ZXJEZWxFbnRpdHlCeVNjZW5lEM0BEjgKM1dvcmxkRXZlbnRU",
            "eXBlX1dvcmxkRXZlbnRUeXBlUGxheWVyQWRkUmVzb3VyY2VQb2ludBDSARI4",
            "CjNXb3JsZEV2ZW50VHlwZV9Xb3JsZEV2ZW50VHlwZVBsYXllckRlbFJlc291",
            "cmNlUG9pbnQQ0wESNAovV29ybGRFdmVudFR5cGVfV29ybGRFdmVudFR5cGVQ",
            "bGF5ZXJBZGRCb3JuUG9pbnQQ1AESNAovV29ybGRFdmVudFR5cGVfV29ybGRF",
            "dmVudFR5cGVQbGF5ZXJEZWxCb3JuUG9pbnQQ1QESJwoiV29ybGRFdmVudFR5",
            "cGVfUzJaTGVzc29uQXJlYUNyZWF0ZRDWARIkCh9Xb3JsZEV2ZW50VHlwZV9T",
            "MlpMZXNzb25BcmVhRGVsENcBEiYKIVdvcmxkRXZlbnRUeXBlX1MyWkxlc3Nv",
            "bkFyZWFRdWVyeRDYARInCiJXb3JsZEV2ZW50VHlwZV9TMlpMZXNzb25BcmVh",
            "VXBkYXRlENkBEicKIldvcmxkRXZlbnRUeXBlX1MyWkJlYXV0eUFyZWFVcGRh",
            "dGUQ2gESJQogV29ybGRFdmVudFR5cGVfUzJaTGVzc29uQXJlYUNvcHkQ2wES",
            "LAonV29ybGRFdmVudFR5cGVfUzJaTGVzc29uQXJlYUluZGV4VXBkYXRlENwB",
            "EicKIldvcmxkRXZlbnRUeXBlX1MyWkxlc3NvbkFyZWFVbmxvY2sQ3QESLgop",
            "V29ybGRFdmVudFR5cGVfUzJaTGVzc29uUGxheWVyQXJyaXZlZEFyZWEQ3gES",
            "MgotV29ybGRFdmVudFR5cGVfUzJaTGVzc29uQXJlYVJ1blF1aWNrQ29kZVN0",
            "YXJ0EN8BEjAKK1dvcmxkRXZlbnRUeXBlX1dvcmxkRXZlbnRUeXBlQWRkVGls",
            "ZU1hcFNpZ24Q4AESMwouV29ybGRFdmVudFR5cGVfV29ybGRFdmVudFR5cGVS",
            "ZW1vdmVUaWxlTWFwU2lnbhDhARIqCiVXb3JsZEV2ZW50VHlwZV9Xb3JsZEV2",
            "ZW50VHlwZVNwYXduQm90EK0CEisKJldvcmxkRXZlbnRUeXBlX1dvcmxkRXZl",
            "bnRUeXBlUmVjYWxsQm90EK4CEi0KKFdvcmxkRXZlbnRUeXBlX1dvcmxkRXZl",
            "bnRUeXBlSXNzdWVTZXR0bGUQkQMSMAorV29ybGRFdmVudFR5cGVfV29ybGRF",
            "dmVudFR5cGVHZXRFbnRpdHlJc3N1ZRCSAxI0Ci9Xb3JsZEV2ZW50VHlwZV9X",
            "b3JsZEV2ZW50VHlwZVdvcmtiZW5jaFVwZGF0ZVN1YhD6AxI3CjJXb3JsZEV2",
            "ZW50VHlwZV9Xb3JsZEV2ZW50VHlwZVdvcmtiZW5jaFVwZGF0ZUZhdGhlchD7",
            "AxIxCixXb3JsZEV2ZW50VHlwZV9Xb3JsZEV2ZW50VHlwZVNwYXduUGFseWVy",
            "QXJlYRDYBBIwCitXb3JsZEV2ZW50VHlwZV9Xb3JsZEV2ZW50VHlwZU1vdmVQ",
            "YWx5ZXJBcmVhENkEEjIKLVdvcmxkRXZlbnRUeXBlX1dvcmxkRXZlbnRUeXBl",
            "UmVtb3ZlUGFseWVyQXJlYRDaBBIzCi5Xb3JsZEV2ZW50VHlwZV9Xb3JsZEV2",
            "ZW50VHlwZVF1ZXJ5TXlQYWx5ZXJBcmVhENsEEi4KKVdvcmxkRXZlbnRUeXBl",
            "X1dvcmxkRXZlbnRUeXBlU2V0R2xvYmFsVmFyENwEEjIKLVdvcmxkRXZlbnRU",
            "eXBlX1dvcmxkRXZlbnRUeXBlUXVlcnlQYWx5ZXJBcmVhcxDdBBI1CjBXb3Js",
            "ZEV2ZW50VHlwZV9Xb3JsZEV2ZW50VHlwZVF1ZXJ5UGFseWVyQXJlYUJ5UmMQ",
            "3gQSHwoaV29ybGRFdmVudFR5cGVfUzJaTWFub3JCdXkQ4gQSJwoiV29ybGRF",
            "dmVudFR5cGVfUzJaTWFub3JCdXlNYXJrU3luYxDjBBIqCiVXb3JsZEV2ZW50",
            "VHlwZV9TMlpNYW5vclRlbXBsYXRlUGFja2V0EOQEEicKIldvcmxkRXZlbnRU",
            "eXBlX1MyWk1hbm9yVGVtcGxhdGVVc2UQ5QQSOQo0V29ybGRFdmVudFR5cGVf",
            "V29ybGRFdmVudFR5cGVUZWFjaGVyUmVzZXRQdWJsaWNNYW5vchDmBBI2CjFX",
            "b3JsZEV2ZW50VHlwZV9Xb3JsZEV2ZW50VHlwZUNyZWF0QXJlYUJ5RW1wdHlB",
            "cmVhEOcEEjQKL1dvcmxkRXZlbnRUeXBlX1dvcmxkRXZlbnRUeXBlTWFub3JU",
            "ZW1wbGF0ZUNoZWNrEOgEEjQKL1dvcmxkRXZlbnRUeXBlX1dvcmxkRXZlbnRU",
            "eXBlQXJlYVVwZGF0ZVRlbXBsYXRlEOkEEi0KKFdvcmxkRXZlbnRUeXBlX1My",
            "WlBsYXllckFyZWFMb2FkTWFub3JNYXAQ6gQSLgopV29ybGRFdmVudFR5cGVf",
            "UzJaTWFub3JUZW1wbGF0ZUNoYW5nZVNpemUQ6wQSKgolV29ybGRFdmVudFR5",
            "cGVfUzJaUGxheWVyTWFub3JUYWtlQmFjaxDsBBI3CjJXb3JsZEV2ZW50VHlw",
            "ZV9Xb3JsZEV2ZW50VHlwZVVwZGF0ZUFyZWFSZWNvdmVyVGltZRDtBBImCiFX",
            "b3JsZEV2ZW50VHlwZV9Xb3JsZEV2ZW50VHlwZVVuZG8QvQUSJgohV29ybGRF",
            "dmVudFR5cGVfV29ybGRFdmVudFR5cGVSZWRvEL4FEjQKL1dvcmxkRXZlbnRU",
            "eXBlX1dvcmxkRXZlbnRUeXBlQ29kZWJsb2NrQWRkRW50aXR5EKEGEjQKL1dv",
            "cmxkRXZlbnRUeXBlX1dvcmxkRXZlbnRUeXBlQ29kZWJsb2NrRGVsRW50aXR5",
            "EKIGEisKJldvcmxkRXZlbnRUeXBlX1dvcmxkRXZlbnRUeXBlQ2xpZW50TXNn",
            "EMlMEi0KKFdvcmxkRXZlbnRUeXBlX1dvcmxkRXZlbnRUeXBlR21BZGRFbnRp",
            "dHkQrU0SPQo4V29ybGRFdmVudFR5cGVfV29ybGRFdmVudFR5cGVQbGF5ZXJB",
            "ZGRCaWdXb3JsZFN5c3RlbUFyZWEQqEYSPQo4V29ybGRFdmVudFR5cGVfV29y",
            "bGRFdmVudFR5cGVQbGF5ZXJEZWxCaWdXb3JsZFN5c3RlbUFyZWEQqUYSKQoj",
            "V29ybGRFdmVudFR5cGVfV29ybGRFdmVudFR5cGVOdW1NYXgQ//8DKmMKDUdy",
            "aWRFdmVudFR5cGUSJgoiR3JpZEV2ZW50VHlwZV9HcmlkRXZlbnRUeXBlVW5r",
            "bm93bhAAEioKJkdyaWRFdmVudFR5cGVfR3JpZEV2ZW50VHlwZUVudGl0eUV2",
            "ZW50EAEq/S0KD0VudGl0eUV2ZW50VHlwZRIqCiZFbnRpdHlFdmVudFR5cGVf",
            "RW50aXR5RXZlbnRUeXBlVW5rbm93bhAAEikKJUVudGl0eUV2ZW50VHlwZV9F",
            "bnRpdHlFdmVudFR5cGVNb3ZlVG8QARIrCidFbnRpdHlFdmVudFR5cGVfRW50",
            "aXR5RXZlbnRUeXBlVXNlU2tpbGwQAhIwCixFbnRpdHlFdmVudFR5cGVfRW50",
            "aXR5RXZlbnRUeXBlQ2hhbmdlQXZhdGFycxADEjAKLEVudGl0eUV2ZW50VHlw",
            "ZV9FbnRpdHlFdmVudFR5cGVVcGRhdGVQcm9maWxlEAQSLgoqRW50aXR5RXZl",
            "bnRUeXBlX0VudGl0eUV2ZW50VHlwZVVwZGF0ZVNraWxsEAUSLgoqRW50aXR5",
            "RXZlbnRUeXBlX0VudGl0eUV2ZW50VHlwZVVwZGF0ZUxldmVsEAYSLQopRW50",
            "aXR5RXZlbnRUeXBlX0VudGl0eUV2ZW50VHlwZVJlY292ZXJ5SHAQBxIrCidF",
            "bnRpdHlFdmVudFR5cGVfRW50aXR5RXZlbnRUeXBlVGVsZXBvcnQQCRIuCipF",
            "bnRpdHlFdmVudFR5cGVfRW50aXR5RXZlbnRUeXBlUGlja0ZhbGxpbmcQCxIq",
            "CiZFbnRpdHlFdmVudFR5cGVfRW50aXR5RXZlbnRUeXBlUGlja0JveBAMEi8K",
            "K0VudGl0eUV2ZW50VHlwZV9FbnRpdHlFdmVudFR5cGVIb21lVGVsZXBvcnQQ",
            "DRIqCiZFbnRpdHlFdmVudFR5cGVfRW50aXR5RXZlbnRUeXBlQWRkQnVmZhAO",
            "Ei0KKUVudGl0eUV2ZW50VHlwZV9FbnRpdHlFdmVudFR5cGVSZW1vdmVCdWZm",
            "EA8SMAosRW50aXR5RXZlbnRUeXBlX0VudGl0eUV2ZW50VHlwZVBsYXllclJl",
            "c3Bhd24QEhI6CjZFbnRpdHlFdmVudFR5cGVfRW50aXR5RXZlbnRUeXBlUGxh",
            "eWVyU2hhcmVCb3RWaWV3U3RhcnQQExI5CjVFbnRpdHlFdmVudFR5cGVfRW50",
            "aXR5RXZlbnRUeXBlUGxheWVyU2hhcmVCb3RWaWV3U3RvcBAUEjQKMEVudGl0",
            "eUV2ZW50VHlwZV9FbnRpdHlFdmVudFR5cGVTMlpQaWNrRmFsbGluZ0JveBAV",
            "EjAKLEVudGl0eUV2ZW50VHlwZV9FbnRpdHlFdmVudFR5cGVQbGF5ZXJVblN0",
            "dWNrEBcSLworRW50aXR5RXZlbnRUeXBlX0VudGl0eUV2ZW50VHlwZUVudGVy",
            "R29kVmlldxAYEi8KK0VudGl0eUV2ZW50VHlwZV9FbnRpdHlFdmVudFR5cGVM",
            "ZWF2ZUdvZFZpZXcQGRI1CjFFbnRpdHlFdmVudFR5cGVfRW50aXR5RXZlbnRU",
            "eXBlVGVsZXBvcnRBbmRUcmlnZ2VyEBoSLgoqRW50aXR5RXZlbnRUeXBlX0Vu",
            "dGl0eUV2ZW50VHlwZVN0YXJ0T3JTdG9wEGASMAosRW50aXR5RXZlbnRUeXBl",
            "X0VudGl0eUV2ZW50VHlwZUVudGVySWRlTW9kZWwQYRIvCitFbnRpdHlFdmVu",
            "dFR5cGVfRW50aXR5RXZlbnRUeXBlUXVpdElkZU1vZGVsEGISLAooRW50aXR5",
            "RXZlbnRUeXBlX0VudGl0eUV2ZW50VHlwZUNsaWVudE1zZxBkEjIKLkVudGl0",
            "eUV2ZW50VHlwZV9FbnRpdHlFdmVudFR5cGVJbnB1dEJ5S2V5cHJlc3MQbhIy",
            "Ci5FbnRpdHlFdmVudFR5cGVfRW50aXR5RXZlbnRUeXBlSW5wdXRCeVNwZWNp",
            "ZmljEG8SKgomRW50aXR5RXZlbnRUeXBlX0VudGl0eUV2ZW50VHlwZVVzZUl0",
            "ZW0QcBIrCidFbnRpdHlFdmVudFR5cGVfRW50aXR5RXZlbnRUeXBlRHJvcEl0",
            "ZW0QcRI2CjJFbnRpdHlFdmVudFR5cGVfRW50aXR5RXZlbnRUeXBlUGxheWVy",
            "RHVuZ2VvblVwZGF0ZRByEjQKMEVudGl0eUV2ZW50VHlwZV9FbnRpdHlFdmVu",
            "dFR5cGVQbGF5ZXJJc3N1ZVNldHRsZRBzEi8KK0VudGl0eUV2ZW50VHlwZV9F",
            "bnRpdHlFdmVudFR5cGVQbGF5ZXJWaWV3VXAQdBIvCitFbnRpdHlFdmVudFR5",
            "cGVfRW50aXR5RXZlbnRUeXBlQ2FtZXJhTW92ZVRvEHYSMgouRW50aXR5RXZl",
            "bnRUeXBlX0VudGl0eUV2ZW50VHlwZUNhbWVyYVNoYXJlVmlldxB3EjIKLkVu",
            "dGl0eUV2ZW50VHlwZV9FbnRpdHlFdmVudFR5cGVQbGF5ZXJTaGFyZVZpZXcQ",
            "eBIzCi9FbnRpdHlFdmVudFR5cGVfRW50aXR5RXZlbnRUeXBlQ2FtZXJhVHlw",
            "ZUNoYW5nZRB5EjEKLUVudGl0eUV2ZW50VHlwZV9FbnRpdHlFdmVudFR5cGVD",
            "YW1lcmFQdWxsVmlldxB6Ei4KKkVudGl0eUV2ZW50VHlwZV9FbnRpdHlFdmVu",
            "dFR5cGVSZXNldFBsYXllchB9EjQKMEVudGl0eUV2ZW50VHlwZV9FbnRpdHlF",
            "dmVudFR5cGVSZXNldExvY2tlZEVudGl0eRB+EjMKLkVudGl0eUV2ZW50VHlw",
            "ZV9FbnRpdHlFdmVudFR5cGVDb2RlTW92ZUFycml2ZWQQyAESMQosRW50aXR5",
            "RXZlbnRUeXBlX0VudGl0eUV2ZW50VHlwZUNvZGVFdmVudENhbGwQzQESOQo0",
            "RW50aXR5RXZlbnRUeXBlX0VudGl0eUV2ZW50VHlwZUNvZGVPbkNvbXBvbmVu",
            "dE9iamVjdBDVARIvCipFbnRpdHlFdmVudFR5cGVfRW50aXR5RXZlbnRUeXBl",
            "UHJvZ3JhbVNhdmUQ1gESMgotRW50aXR5RXZlbnRUeXBlX0VudGl0eUV2ZW50",
            "VHlwZUNvZGVTY3JlZW5TYXZlENcBEi8KKkVudGl0eUV2ZW50VHlwZV9FbnRp",
            "dHlFdmVudFR5cGVDb2RlUmVzdGFydBDYARI1CjBFbnRpdHlFdmVudFR5cGVf",
            "RW50aXR5RXZlbnRUeXBlQ29kZU9uRW5lcmd5RW1wdHkQ2QESMQosRW50aXR5",
            "RXZlbnRUeXBlX0VudGl0eUV2ZW50VHlwZUNvZGVPbkNvcHlOZXcQ2gESMQos",
            "RW50aXR5RXZlbnRUeXBlX0VudGl0eUV2ZW50VHlwZUNvZGVPbkNvcHlEZWwQ",
            "2wESNgoxRW50aXR5RXZlbnRUeXBlX0VudGl0eUV2ZW50VHlwZUNvZGVRdWVz",
            "dGlvblJlcGxheRDcARI5CjRFbnRpdHlFdmVudFR5cGVfRW50aXR5RXZlbnRU",
            "eXBlQ29kZUV4ZWN1dGVTdGFydEV2ZW50EN0BEjUKMEVudGl0eUV2ZW50VHlw",
            "ZV9FbnRpdHlFdmVudFR5cGVDb2RlU3RvcENvZGVCbG9jaxDeARIxCixFbnRp",
            "dHlFdmVudFR5cGVfRW50aXR5RXZlbnRUeXBlQ29kZUVudGl0eUFkZBDgARI3",
            "CjJFbnRpdHlFdmVudFR5cGVfRW50aXR5RXZlbnRUeXBlQ29kZU9uRW50aXR5",
            "T3ZlcmxhcBDhARIyCi1FbnRpdHlFdmVudFR5cGVfRW50aXR5RXZlbnRUeXBl",
            "Q29kZU9uU3RhbXBlZGUQ5AESNQowRW50aXR5RXZlbnRUeXBlX0VudGl0eUV2",
            "ZW50VHlwZUNvZGVPblN0YW1wZWRlRW5kEOUBEjYKMUVudGl0eUV2ZW50VHlw",
            "ZV9FbnRpdHlFdmVudFR5cGVDb2RlU2V0Q2FuU3RhbXBlZGUQ5gESNQowRW50",
            "aXR5RXZlbnRUeXBlX0VudGl0eUV2ZW50VHlwZUNvZGVTZXRDYW5PcGVyYXRl",
            "EOcBEjMKLkVudGl0eUV2ZW50VHlwZV9FbnRpdHlFdmVudFR5cGVDb2RlT25C",
            "eUNsaWNrZWQQ7QESMwouRW50aXR5RXZlbnRUeXBlX0VudGl0eUV2ZW50VHlw",
            "ZUNvZGVPbkVudGVyUm9vbRDuARI2CjFFbnRpdHlFdmVudFR5cGVfRW50aXR5",
            "RXZlbnRUeXBlQ29kZUNvcHlGYXRoZXJEZWFkEO8BEjQKL0VudGl0eUV2ZW50",
            "VHlwZV9FbnRpdHlFdmVudFR5cGVDb2RlRWRpdFRpbWVMaW5lEPABEjQKL0Vu",
            "dGl0eUV2ZW50VHlwZV9FbnRpdHlFdmVudFR5cGVUaW1lTGluZVNob3dUZXh0",
            "EPEBEjUKMEVudGl0eUV2ZW50VHlwZV9FbnRpdHlFdmVudFR5cGVUaW1lTGlu",
            "ZU1vdmVUb1BvcxDyARI1CjBFbnRpdHlFdmVudFR5cGVfRW50aXR5RXZlbnRU",
            "eXBlVGltZUxpbmVQbGF5QXVkaW8Q8wESOAozRW50aXR5RXZlbnRUeXBlX0Vu",
            "dGl0eUV2ZW50VHlwZVRpbWVMaW5lU2hvd1N1YnRpdGxlEPQBEjIKLUVudGl0",
            "eUV2ZW50VHlwZV9FbnRpdHlFdmVudFR5cGVDb2RlQ0dWaWRlb0VuZBD1ARI0",
            "Ci9FbnRpdHlFdmVudFR5cGVfRW50aXR5RXZlbnRUeXBlUXVpY2tDb2RlUmVz",
            "dGFydBD2ARIoCiNFbnRpdHlFdmVudFR5cGVfRW50aXR5RXZlbnRUeXBlSGlk",
            "ZRD3ARI9CjhFbnRpdHlFdmVudFR5cGVfRW50aXR5RXZlbnRUeXBlQ29kZUV2",
            "ZW50Q29kZU5vdGlmaWNhdGlvbhDjAhIyCi1FbnRpdHlFdmVudFR5cGVfRW50",
            "aXR5RXZlbnRUeXBlQ29kZVNldFByb2ZpbGUQ5QISNAovRW50aXR5RXZlbnRU",
            "eXBlX0VudGl0eUV2ZW50VHlwZUNvZGVTZXR0aW5nUGFuZWwQ5gISMgotRW50",
            "aXR5RXZlbnRUeXBlX0VudGl0eUV2ZW50VHlwZUNvZGVNaXNzaW9uRW5kEOcC",
            "EjYKMUVudGl0eUV2ZW50VHlwZV9FbnRpdHlFdmVudFR5cGVDbGlja09wZXJh",
            "dGVCdWJibGUQ6AISNAovRW50aXR5RXZlbnRUeXBlX0VudGl0eUV2ZW50VHlw",
            "ZUNvZGVDYW1lcmFBY3Rpb24Q6QISNAovRW50aXR5RXZlbnRUeXBlX0VudGl0",
            "eUV2ZW50VHlwZVBvcENvbXBsZXhEaWdsb2cQ6gISNQowRW50aXR5RXZlbnRU",
            "eXBlX0VudGl0eUV2ZW50VHlwZUNvZGVTZXRDYXJyeUNsYXNzEOsCEjUKMEVu",
            "dGl0eUV2ZW50VHlwZV9FbnRpdHlFdmVudFR5cGVCb3RTaGFyZVZpZXdTdGFy",
            "dBCQAxI0Ci9FbnRpdHlFdmVudFR5cGVfRW50aXR5RXZlbnRUeXBlQm90U2hh",
            "cmVWaWV3U3RvcBCRAxIrCiZFbnRpdHlFdmVudFR5cGVfRW50aXR5RXZlbnRU",
            "eXBlQWRkRnVlbBCTAxIxCixFbnRpdHlFdmVudFR5cGVfRW50aXR5RXZlbnRU",
            "eXBlQm90Q2hhbmdlU2tpbhCUAxItCihFbnRpdHlFdmVudFR5cGVfRW50aXR5",
            "RXZlbnRUeXBlQm90UmVuYW1lEJUDEjIKLUVudGl0eUV2ZW50VHlwZV9FbnRp",
            "dHlFdmVudFR5cGVCdWlsZGluZ1N3aXRjaBDCAxI5CjRFbnRpdHlFdmVudFR5",
            "cGVfRW50aXR5RXZlbnRUeXBlQnVpbGRpbmdNb2RlUG9zVXBkYXRlEMMDEjYK",
            "MUVudGl0eUV2ZW50VHlwZV9FbnRpdHlFdmVudFR5cGVRdWl0QnVpbGRpbmdT",
            "dGF0dXMQxAMSOQo0RW50aXR5RXZlbnRUeXBlX0VudGl0eUV2ZW50VHlwZVdv",
            "cmtiZW5jaE9iamVjdFVwZGF0ZRD1AxI4CjNFbnRpdHlFdmVudFR5cGVfRW50",
            "aXR5RXZlbnRUeXBlQnVpbGRpbmdXaWRnZXRVcGRhdGUQ9gMSNAovRW50aXR5",
            "RXZlbnRUeXBlX0VudGl0eUV2ZW50VHlwZVdvcmtiZW5jaEFkZEZ1ZWwQgAQS",
            "NgoxRW50aXR5RXZlbnRUeXBlX0VudGl0eUV2ZW50VHlwZVdvcmtiZW5jaENv",
            "bXBvbmVudBCBBBI7CjZFbnRpdHlFdmVudFR5cGVfRW50aXR5RXZlbnRUeXBl",
            "V29ya2JlbmNoUmVzZXRDb21wb25lbnQQggQSNgoxRW50aXR5RXZlbnRUeXBl",
            "X0VudGl0eUV2ZW50VHlwZVdvcmtiZW5jaFNldFByb21wdBCDBBI2CjFFbnRp",
            "dHlFdmVudFR5cGVfRW50aXR5RXZlbnRUeXBlV29ya2JlbmNoVXBkYXRlU3Vi",
            "EIQEEjkKNEVudGl0eUV2ZW50VHlwZV9FbnRpdHlFdmVudFR5cGVXb3JrYmVu",
            "Y2hVcGRhdGVGYXRoZXIQhQQSLgopRW50aXR5RXZlbnRUeXBlX0VudGl0eUV2",
            "ZW50VHlwZUVudGl0eUxvY2sQ2AQSMAorRW50aXR5RXZlbnRUeXBlX0VudGl0",
            "eUV2ZW50VHlwZUVudGl0eVVuTG9jaxDZBBI7CjZFbnRpdHlFdmVudFR5cGVf",
            "RW50aXR5RXZlbnRUeXBlUmVnaXN0ZXJFbnRpdHlDb2RlRXZlbnQQ2gQSOgo1",
            "RW50aXR5RXZlbnRUeXBlX0VudGl0eUV2ZW50VHlwZURlc3Ryb3lFbnRpdHlD",
            "b2RlRXZlbnQQ2wQSKwomRW50aXR5RXZlbnRUeXBlX0VudGl0eUV2ZW50VHlw",
            "ZUJlQ2xpY2sQ3AQSMwouRW50aXR5RXZlbnRUeXBlX0VudGl0eUV2ZW50VHlw",
            "ZVVwZGF0ZUFuaW1hdGlvbhDdBBIuCilFbnRpdHlFdmVudFR5cGVfRW50aXR5",
            "RXZlbnRUeXBlQmVPcGVyYXRlZBDeBBI0Ci9FbnRpdHlFdmVudFR5cGVfRW50",
            "aXR5RXZlbnRUeXBlRW50aXR5TG9ja1VwZGF0ZRDfBBIvCipFbnRpdHlFdmVu",
            "dFR5cGVfRW50aXR5RXZlbnRUeXBlVXBkYXRlQXVkaW8Q4AQSNQowRW50aXR5",
            "RXZlbnRUeXBlX0VudGl0eUV2ZW50VHlwZVBsYXllckFkZERpeUF1ZGlvEOEE",
            "EjUKMEVudGl0eUV2ZW50VHlwZV9FbnRpdHlFdmVudFR5cGVQbGF5ZXJHZXRE",
            "aXlBdWRpbxDiBBIyCi1FbnRpdHlFdmVudFR5cGVfRW50aXR5RXZlbnRUeXBl",
            "VXBkYXRlVXNlRW1vamkQ4wQSNwoyRW50aXR5RXZlbnRUeXBlX0VudGl0eUV2",
            "ZW50VHlwZUFwcGx5RW50aXR5VGVtcGxhdGUQ5AQSNQowRW50aXR5RXZlbnRU",
            "eXBlX0VudGl0eUV2ZW50VHlwZVVwZGF0ZU1hcFRlbXBsYXRlEOUEEjUKMEVu",
            "dGl0eUV2ZW50VHlwZV9FbnRpdHlFdmVudFR5cGVNb25zdGVyTG9ja1BsYXll",
            "chDmBBI4CjNFbnRpdHlFdmVudFR5cGVfRW50aXR5RXZlbnRUeXBlUGxheWVy",
            "Rm9yY2VFeGl0RmlnaHQQ5wQSMgotRW50aXR5RXZlbnRUeXBlX0VudGl0eUV2",
            "ZW50VHlwZVNlbmROZWFyYnlDaGF0EOgHEj4KOUVudGl0eUV2ZW50VHlwZV9F",
            "bnRpdHlFdmVudFR5cGVTZW5kTmVhclRvQ29kZUVudGl0eWJ5Q2hhdBDpBxIr",
            "CiVFbnRpdHlFdmVudFR5cGVfRW50aXR5RXZlbnRUeXBlTnVtTWF4EP//Ayrm",
            "AQoNRXZlbnRDb2RlVHlwZRImCiJFdmVudENvZGVUeXBlX0V2ZW50Q29kZVR5",
            "cGVVbmtub3duEAASJQohRXZlbnRDb2RlVHlwZV9FdmVudENvZGVUeXBlU2Vy",
            "dmVyEAESKgomRXZlbnRDb2RlVHlwZV9FdmVudENvZGVUeXBlRW50aXR5RXZl",
            "bnQQAhIvCitFdmVudENvZGVUeXBlX0V2ZW50Q29kZVR5cGVSZWNlaXZlRXZl",
            "bnRDYWxsEAMSKQolRXZlbnRDb2RlVHlwZV9FdmVudENvZGVUeXBlRW50aXR5",
            "VHlwZRAEKocOChNFbnRpdHlDb2RlRXZlbnRUeXBlEjIKLkVudGl0eUNvZGVF",
            "dmVudFR5cGVfRW50aXR5Q29kZUV2ZW50VHlwZVVua25vd24QABI0CjBFbnRp",
            "dHlDb2RlRXZlbnRUeXBlX0VudGl0eUNvZGVFdmVudFR5cGVCZUNsaWNrZWQQ",
            "ZRI0CjBFbnRpdHlDb2RlRXZlbnRUeXBlX0VudGl0eUNvZGVFdmVudFR5cGVQ",
            "b3NVcGRhdGUQZhIzCi9FbnRpdHlDb2RlRXZlbnRUeXBlX0VudGl0eUNvZGVF",
            "dmVudFR5cGVCZUF0dGFjaxBnEjEKLUVudGl0eUNvZGVFdmVudFR5cGVfRW50",
            "aXR5Q29kZUV2ZW50VHlwZUF0dGFjaxBoEi8KK0VudGl0eUNvZGVFdmVudFR5",
            "cGVfRW50aXR5Q29kZUV2ZW50VHlwZURlYWQQaRIyCi5FbnRpdHlDb2RlRXZl",
            "bnRUeXBlX0VudGl0eUNvZGVFdmVudFR5cGVPblRvdWNoEGoSNgoyRW50aXR5",
            "Q29kZUV2ZW50VHlwZV9FbnRpdHlDb2RlRXZlbnRUeXBlRnJhbWVVcGRhdGUQ",
            "axI1CjFFbnRpdHlDb2RlRXZlbnRUeXBlX0VudGl0eUNvZGVFdmVudFR5cGVG",
            "dWVsVXBkYXRlEGwSMwovRW50aXR5Q29kZUV2ZW50VHlwZV9FbnRpdHlDb2Rl",
            "RXZlbnRUeXBlVXNlU2tpbGwQbRI1CjFFbnRpdHlDb2RlRXZlbnRUeXBlX0Vu",
            "dGl0eUNvZGVFdmVudFR5cGVDYW5PcGVyYXRlEG4SMQotRW50aXR5Q29kZUV2",
            "ZW50VHlwZV9FbnRpdHlDb2RlRXZlbnRUeXBlTWlycm9yEHASNAowRW50aXR5",
            "Q29kZUV2ZW50VHlwZV9FbnRpdHlDb2RlRXZlbnRUeXBlQ29tcG9uZW50EHES",
            "Owo3RW50aXR5Q29kZUV2ZW50VHlwZV9FbnRpdHlDb2RlRXZlbnRUeXBlUmVj",
            "ZWl2ZUV2ZW50Q2FsbBByEjQKMEVudGl0eUNvZGVFdmVudFR5cGVfRW50aXR5",
            "Q29kZUV2ZW50VHlwZVZhckNoYW5nZRBzEjsKN0VudGl0eUNvZGVFdmVudFR5",
            "cGVfRW50aXR5Q29kZUV2ZW50VHlwZUVudGl0eUJlU3RhbXBlZGUQdBI/CjtF",
            "bnRpdHlDb2RlRXZlbnRUeXBlX0VudGl0eUNvZGVFdmVudFR5cGVFbnRpdHlP",
            "dmVyQmVTdGFtcGVkZRB1EjIKLkVudGl0eUNvZGVFdmVudFR5cGVfRW50aXR5",
            "Q29kZUV2ZW50VHlwZU9uQnVpbGQQdhI0CjBFbnRpdHlDb2RlRXZlbnRUeXBl",
            "X0VudGl0eUNvZGVFdmVudFR5cGVFbnRlclJvb20QdxI5CjVFbnRpdHlDb2Rl",
            "RXZlbnRUeXBlX0VudGl0eUNvZGVFdmVudFR5cGVJbnB1dEtleUFjdGlvbhB5",
            "EjMKL0VudGl0eUNvZGVFdmVudFR5cGVfRW50aXR5Q29kZUV2ZW50VHlwZUtl",
            "eXByZXNzEHoSMgouRW50aXR5Q29kZUV2ZW50VHlwZV9FbnRpdHlDb2RlRXZl",
            "bnRUeXBlVXNlSXRlbRB8EjMKL0VudGl0eUNvZGVFdmVudFR5cGVfRW50aXR5",
            "Q29kZUV2ZW50VHlwZURyb3BJdGVtEH0SNQoxRW50aXR5Q29kZUV2ZW50VHlw",
            "ZV9FbnRpdHlDb2RlRXZlbnRUeXBlUGlja3VwSXRlbRB+EjMKLkVudGl0eUNv",
            "ZGVFdmVudFR5cGVfRW50aXR5Q29kZUV2ZW50VHlwZU9uQ3Jhc2gQgQESOgo1",
            "RW50aXR5Q29kZUV2ZW50VHlwZV9FbnRpdHlDb2RlRXZlbnRUeXBlRHJvcEl0",
            "ZW1XaXRoSWQQggESNgoxRW50aXR5Q29kZUV2ZW50VHlwZV9FbnRpdHlDb2Rl",
            "RXZlbnRUeXBlT25DbG9uZURlbBCDARI2CjFFbnRpdHlDb2RlRXZlbnRUeXBl",
            "X0VudGl0eUV2ZW50VHlwZUNvZGVPbkJlUGlja1VwEIcBEjcKMkVudGl0eUNv",
            "ZGVFdmVudFR5cGVfRW50aXR5RXZlbnRUeXBlQ29kZU9uQmVQdXREb3duEIgB",
            "EjcKMkVudGl0eUNvZGVFdmVudFR5cGVfRW50aXR5RXZlbnRUeXBlQ29kZU9u",
            "QmVEZXN0cm95EIkBEj0KOEVudGl0eUNvZGVFdmVudFR5cGVfRW50aXR5RXZl",
            "bnRUeXBlQ29kZVBsYXllcklzc3VlU2V0dGxlEIoBEkIKPUVudGl0eUNvZGVF",
            "dmVudFR5cGVfRW50aXR5RXZlbnRUeXBlRW50aXRpZXNRdWlja0NvZGVSdW5P",
            "clN0b3AQiwEqWgoMRGF0YVNhdmVUeXBlEiQKIERhdGFTYXZlVHlwZV9EYXRh",
            "U2F2ZVR5cGVVbmtub3duEAASJAofRGF0YVNhdmVUeXBlX0RhdGFTYXZlVHlw",
            "ZU1hcEdvYhDpByqkAgoUU2NlbmVGb3JjZVJlbW92ZVRpbWUSNAowU2NlbmVG",
            "b3JjZVJlbW92ZVRpbWVfU2NlbmVGb3JjZVJlbW92ZVRpbWVVbmtub3duEAAS",
            "MwouU2NlbmVGb3JjZVJlbW92ZVRpbWVfU2NlbmVGb3JjZVJlbW92ZVRpbWVM",
            "ZWF2ZRDRDxI2CjFTY2VuZUZvcmNlUmVtb3ZlVGltZV9TY2VuZUZvcmNlUmVt",
            "b3ZlVGltZVRhcmdldFJDENIPEjUKMFNjZW5lRm9yY2VSZW1vdmVUaW1lX1Nj",
            "ZW5lRm9yY2VSZW1vdmVUaW1lUnVuVGltZRDTDxIyCi1TY2VuZUZvcmNlUmVt",
            "b3ZlVGltZV9TY2VuZUZvcmNlUmVtb3ZlVGltZURpc3QQ1A9iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::MelandGame3.ServerMsgEventType), typeof(global::MelandGame3.ServerEventType), typeof(global::MelandGame3.WorldEventType), typeof(global::MelandGame3.GridEventType), typeof(global::MelandGame3.EntityEventType), typeof(global::MelandGame3.EventCodeType), typeof(global::MelandGame3.EntityCodeEventType), typeof(global::MelandGame3.DataSaveType), typeof(global::MelandGame3.SceneForceRemoveTime), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum ServerMsgEventType {
    /// <summary>
    /// 未知类型
    /// </summary>
    [pbr::OriginalName("ServerMsgEventType_ServerMsgEventTypeUnknow")] ServerMsgEventTypeUnknow = 0,
    /// <summary>
    /// 收到消息
    /// </summary>
    [pbr::OriginalName("ServerMsgEventType_ServerMsgEventTypeReceiveMsg")] ServerMsgEventTypeReceiveMsg = 1,
    /// <summary>
    /// 触发回调
    /// </summary>
    [pbr::OriginalName("ServerMsgEventType_ServerMsgEventTypeCallBack")] ServerMsgEventTypeCallBack = 2,
    /// <summary>
    /// 消息超时
    /// </summary>
    [pbr::OriginalName("ServerMsgEventType_ServerMsgEventTypeTimeOut")] ServerMsgEventTypeTimeOut = 3,
  }

  public enum ServerEventType {
    [pbr::OriginalName("ServerEventType_ServerEventTypeServerUnknown")] ServerEventTypeServerUnknown = 0,
    /// <summary>
    /// 服务器驱动事件 10-99
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventTypeServerAfterConfig")] ServerEventTypeServerAfterConfig = 10,
    [pbr::OriginalName("ServerEventType_ServerEventTypeServerMinutely")] ServerEventTypeServerMinutely = 11,
    [pbr::OriginalName("ServerEventType_ServerEventTypeServerHourly")] ServerEventTypeServerHourly = 12,
    [pbr::OriginalName("ServerEventType_ServerEventTypeServerDaily")] ServerEventTypeServerDaily = 13,
    [pbr::OriginalName("ServerEventType_ServerEventTypeServerConnClose")] ServerEventTypeServerConnClose = 14,
    [pbr::OriginalName("ServerEventType_ServerEventTypeServerConnConnect")] ServerEventTypeServerConnConnect = 15,
    [pbr::OriginalName("ServerEventType_ServerEventTypeServerTimer")] ServerEventTypeServerTimer = 16,
    [pbr::OriginalName("ServerEventType_ServerEventTypeSqlRollBack")] ServerEventTypeSqlRollBack = 17,
    [pbr::OriginalName("ServerEventType_ServerEventTypeServerEventCall")] ServerEventTypeServerEventCall = 18,
    /// <summary>
    /// -------------------------------------------------------------------------
    /// 角色事件 100-199
    /// -------------------------------------------------------------------------
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventTypePlayerCreated")] ServerEventTypePlayerCreated = 100,
    [pbr::OriginalName("ServerEventType_ServerEventTypePlayerOnline")] ServerEventTypePlayerOnline = 101,
    [pbr::OriginalName("ServerEventType_ServerEventTypePlayerOffline")] ServerEventTypePlayerOffline = 102,
    [pbr::OriginalName("ServerEventType_ServerEventTypePlayerNewDay")] ServerEventTypePlayerNewDay = 103,
    [pbr::OriginalName("ServerEventType_ServerEventTypePlayerLvUp")] ServerEventTypePlayerLvUp = 104,
    [pbr::OriginalName("ServerEventType_ServerEventTypePlayerResetProfile")] ServerEventTypePlayerResetProfile = 105,
    /// <summary>
    /// 技能更新
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventTypePlayerUpdateSkill")] ServerEventTypePlayerUpdateSkill = 106,
    /// <summary>
    /// exp增加
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventTypePlayerAddExp")] ServerEventTypePlayerAddExp = 107,
    /// <summary>
    /// exp扣除
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventTypePlayerDeductExp")] ServerEventTypePlayerDeductExp = 108,
    /// <summary>
    /// HP回复
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventTypePlayerReplyHp")] ServerEventTypePlayerReplyHp = 109,
    [pbr::OriginalName("ServerEventType_ServerEventTypeCalculatePlayerProfile")] ServerEventTypeCalculatePlayerProfile = 110,
    /// <summary>
    /// 玩家使用技能
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventTypePlayerUseSkill")] ServerEventTypePlayerUseSkill = 111,
    /// <summary>
    /// 玩家被攻击
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventTypePlayerBeAttack")] ServerEventTypePlayerBeAttack = 112,
    /// <summary>
    /// 销毁item
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventTypeDestoryItem")] ServerEventTypeDestoryItem = 114,
    /// <summary>
    /// 销毁所有item
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventTypeDestoryAllItem")] ServerEventTypeDestoryAllItem = 115,
    /// <summary>
    /// 添加item
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventTypeAddItem")] ServerEventTypeAddItem = 116,
    /// <summary>
    /// 玩家兑换cdkey
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventTypeRedeemCDKey")] ServerEventTypeRedeemCdkey = 117,
    /// <summary>
    /// 玩家神庙等级升级
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventTypeDungeon")] ServerEventTypeDungeon = 118,
    /// <summary>
    /// send chat message
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventTypeSendChatMsg")] ServerEventTypeSendChatMsg = 119,
    [pbr::OriginalName("ServerEventType_ServerEventTypeSendUpdateChatState")] ServerEventTypeSendUpdateChatState = 120,
    [pbr::OriginalName("ServerEventType_ServerEventTypeSendRemoveChatMsg")] ServerEventTypeSendRemoveChatMsg = 121,
    /// <summary>
    /// -------------------------------------------------------------------------
    /// 来自场景的通知 200-1000
    /// -------------------------------------------------------------------------
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventZoneSendToPlayer")] ServerEventZoneSendToPlayer = 200,
    [pbr::OriginalName("ServerEventType_Z2SZoneBroadcast")] Z2SzoneBroadcast = 202,
    [pbr::OriginalName("ServerEventType_ServerEventEntityAnimationCreate")] ServerEventEntityAnimationCreate = 203,
    [pbr::OriginalName("ServerEventType_ServerEventEntityAnimationUpdate")] ServerEventEntityAnimationUpdate = 204,
    [pbr::OriginalName("ServerEventType_ServerEventEntityAnimationDel")] ServerEventEntityAnimationDel = 205,
    [pbr::OriginalName("ServerEventType_Z2SGobMapSave")] Z2SgobMapSave = 206,
    [pbr::OriginalName("ServerEventType_ServerEventEntityPlayerUpdate")] ServerEventEntityPlayerUpdate = 207,
    [pbr::OriginalName("ServerEventType_Z2SEntityTemplateSave")] Z2SentityTemplateSave = 208,
    [pbr::OriginalName("ServerEventType_Z2SPlayerOffline")] Z2SplayerOffline = 210,
    [pbr::OriginalName("ServerEventType_Z2SPlayerManorData")] Z2SplayerManorData = 211,
    /// <summary>
    ///保存实体
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventEntitySave")] ServerEventEntitySave = 213,
    /// <summary>
    /// 建造
    /// </summary>
    [pbr::OriginalName("ServerEventType_Z2SBuildDelete")] Z2SbuildDelete = 242,
    [pbr::OriginalName("ServerEventType_ServerEventBuild")] ServerEventBuild = 243,
    [pbr::OriginalName("ServerEventType_Z2SPuppetDelete")] Z2SpuppetDelete = 244,
    /// <summary>
    ///数据落地
    /// </summary>
    [pbr::OriginalName("ServerEventType_Z2SPlayerSave")] Z2SplayerSave = 399,
    [pbr::OriginalName("ServerEventType_Z2SEntitySave")] Z2SentitySave = 400,
    [pbr::OriginalName("ServerEventType_Z2SManorPacket")] Z2SmanorPacket = 401,
    /// <summary>
    /// 代码块 500-700
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventCodeExecute")] ServerEventCodeExecute = 500,
    [pbr::OriginalName("ServerEventType_ServerEventUseItemFromZone")] ServerEventUseItemFromZone = 501,
    [pbr::OriginalName("ServerEventType_ServerEventDropItemFromZone")] ServerEventDropItemFromZone = 502,
    [pbr::OriginalName("ServerEventType_ServerEventBotBuildFromZone")] ServerEventBotBuildFromZone = 503,
    [pbr::OriginalName("ServerEventType_ServerEventMakeItemFromZone")] ServerEventMakeItemFromZone = 505,
    [pbr::OriginalName("ServerEventType_ServerEventTakeWorkbenchItemByCidFromZone")] ServerEventTakeWorkbenchItemByCidFromZone = 506,
    [pbr::OriginalName("ServerEventType_ServerEventGiveWorkbenchItemByCidFromZone")] ServerEventGiveWorkbenchItemByCidFromZone = 507,
    [pbr::OriginalName("ServerEventType_ServerEventPlayerCompleteChapter")] ServerEventPlayerCompleteChapter = 508,
    [pbr::OriginalName("ServerEventType_ServerEventMissionEnter")] ServerEventMissionEnter = 509,
    [pbr::OriginalName("ServerEventType_ServerEventAcceptTask")] ServerEventAcceptTask = 510,
    [pbr::OriginalName("ServerEventType_ServerEventSubmitTask")] ServerEventSubmitTask = 511,
    [pbr::OriginalName("ServerEventType_ServerEventComplateTask")] ServerEventComplateTask = 512,
    [pbr::OriginalName("ServerEventType_ServerEventMissionEnterSceneMonitor")] ServerEventMissionEnterSceneMonitor = 513,
    /// <summary>
    /// 战斗
    ///ServerEventType_Z2S_PickItem = 711;
    /// </summary>
    [pbr::OriginalName("ServerEventType_Z2S_PlayerDead")] Z2SPlayerDead = 712,
    [pbr::OriginalName("ServerEventType_ServerEventZ2SAddExpToBot")] ServerEventZ2SaddExpToBot = 715,
    /// <summary>
    /// 机器人
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventZ2SBotDead")] ServerEventZ2SbotDead = 731,
    /// <summary>
    /// 工作台
    /// </summary>
    [pbr::OriginalName("ServerEventType_Z2SPlantDelete")] Z2SplantDelete = 753,
    [pbr::OriginalName("ServerEventType_Z2SPetDelete")] Z2SpetDelete = 754,
    /// <summary>
    /// -------------------------------------------------------------------------
    /// (机器人)事件 800-899
    /// -------------------------------------------------------------------------
    /// (机器人)更换装备
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventTypeBotCreated")] ServerEventTypeBotCreated = 800,
    /// <summary>
    /// (机器人)升级
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventTypeBotLvUp")] ServerEventTypeBotLvUp = 801,
    /// <summary>
    /// (机器人)更换装备
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventTypeUpdateBotEquipment")] ServerEventTypeUpdateBotEquipment = 802,
    /// <summary>
    /// exp增加
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventTypeBotAddExp")] ServerEventTypeBotAddExp = 803,
    /// <summary>
    /// HP回复
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventTypeBotReplyHp")] ServerEventTypeBotReplyHp = 804,
    /// <summary>
    /// bot背包添加物品
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventTypeBotAddObject")] ServerEventTypeBotAddObject = 805,
    /// <summary>
    /// 召回机器人
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventTypeRecallBot")] ServerEventTypeRecallBot = 806,
    /// <summary>
    /// 机器人使用技能
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventTypeBotUseSkill")] ServerEventTypeBotUseSkill = 807,
    /// <summary>
    /// 玩家被攻击
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventTypeBotBeAttack")] ServerEventTypeBotBeAttack = 808,
    /// <summary>
    /// 添加物品（带属性的）
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventTypeBotAddItem")] ServerEventTypeBotAddItem = 809,
    /// <summary>
    /// -------------------------------------------------------------------------
    /// 背包event协议号 900 - 999
    /// -------------------------------------------------------------------------
    /// 使用消耗品
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventTypePlayerUseConsumable")] ServerEventTypePlayerUseConsumable = 902,
    /// <summary>
    /// 添加物品
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventTypePlayerAddObject")] ServerEventTypePlayerAddObject = 903,
    /// <summary>
    /// 拾取物品
    /// </summary>
    [pbr::OriginalName("ServerEventType_Z2SPickFalling")] Z2SpickFalling = 904,
    /// <summary>
    /// 拾取包裹
    /// </summary>
    [pbr::OriginalName("ServerEventType_Z2SPickFallingBox")] Z2SpickFallingBox = 905,
    [pbr::OriginalName("ServerEventType_ServerEventTypePlayerUseObject")] ServerEventTypePlayerUseObject = 907,
    [pbr::OriginalName("ServerEventType_ServerEventTypeAddItemByOperateBubble")] ServerEventTypeAddItemByOperateBubble = 908,
    [pbr::OriginalName("ServerEventType_ServerEventTypeTakeItemByOperateBubble")] ServerEventTypeTakeItemByOperateBubble = 909,
    [pbr::OriginalName("ServerEventType_ServerEventTypeReplaceItemByOperateBubble")] ServerEventTypeReplaceItemByOperateBubble = 910,
    /// <summary>
    /// 重置玩家nft道具的使用状态
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventTypeResetPlayerNftStatus")] ServerEventTypeResetPlayerNftStatus = 911,
    [pbr::OriginalName("ServerEventType_ServerEventTypeUpdatePlayerNFTs")] ServerEventTypeUpdatePlayerNfts = 912,
    /// <summary>
    /// 更新第三方nft道具的过期时间
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventTypeUpdateThirdNftTimeOut")] ServerEventTypeUpdateThirdNftTimeOut = 915,
    /// <summary>
    /// -------------------------------------------------------------------------
    /// 任务系统 1000-1050
    /// -------------------------------------------------------------------------
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventTypePlayerAcceptedTask")] ServerEventTypePlayerAcceptedTask = 1001,
    [pbr::OriginalName("ServerEventType_ServerEventTypePlayerSubmittedTask")] ServerEventTypePlayerSubmittedTask = 1002,
    [pbr::OriginalName("ServerEventType_ServerEventTypeUpdateNpcTaskNoticeType")] ServerEventTypeUpdateNpcTaskNoticeType = 1003,
    [pbr::OriginalName("ServerEventType_ServerEventTypePlayerTaskStateUpdate")] ServerEventTypePlayerTaskStateUpdate = 1005,
    /// <summary>
    /// 任务
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventTaskProgressChange")] ServerEventTaskProgressChange = 1049,
    /// <summary>
    /// -------------------------------------------------------------------------
    /// 邮件event协议号 1050 - 1100
    /// -------------------------------------------------------------------------
    /// 添加个人邮件
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventTypePlayerAddMail")] ServerEventTypePlayerAddMail = 1051,
    /// <summary>
    /// 添加全服邮件
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventTypeServerSendMailByTemplateId")] ServerEventTypeServerSendMailByTemplateId = 1052,
    /// <summary>
    /// -------------------------------------------------------------------------
    /// 大世界event协议号 9000 - 10000
    /// -------------------------------------------------------------------------
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventTypeLandGroupCreate")] ServerEventTypeLandGroupCreate = 9000,
    [pbr::OriginalName("ServerEventType_ServerEventTypeLandGroupUpdate")] ServerEventTypeLandGroupUpdate = 9001,
    [pbr::OriginalName("ServerEventType_ServerEventTypeLandGroupRemove")] ServerEventTypeLandGroupRemove = 9002,
    /// <summary>
    /// -------------------------------------------------------------------------
    /// 最大事件数
    /// </summary>
    [pbr::OriginalName("ServerEventType_ServerEventTypeNumMax")] ServerEventTypeNumMax = 65535,
  }

  public enum WorldEventType {
    /// <summary>
    /// 场景事件
    /// </summary>
    [pbr::OriginalName("WorldEventType_WorldEventTypeUnknown")] WorldEventTypeUnknown = 0,
    [pbr::OriginalName("WorldEventType_WorldEventTypeSendToZone")] WorldEventTypeSendToZone = 1,
    [pbr::OriginalName("WorldEventType_WorldEventTypeEnterMap")] WorldEventTypeEnterMap = 2,
    [pbr::OriginalName("WorldEventType_WorldEventTypeLeaveMap")] WorldEventTypeLeaveMap = 3,
    [pbr::OriginalName("WorldEventType_WorldEventTypeMove")] WorldEventTypeMove = 4,
    [pbr::OriginalName("WorldEventType_WorldEventTypeMapSave")] WorldEventTypeMapSave = 5,
    [pbr::OriginalName("WorldEventType_WorldEventTypeReloadResourcePoint")] WorldEventTypeReloadResourcePoint = 6,
    [pbr::OriginalName("WorldEventType_WorldEventTypeInitMapElement")] WorldEventTypeInitMapElement = 7,
    [pbr::OriginalName("WorldEventType_WorldEventTypeEntitySave")] WorldEventTypeEntitySave = 8,
    [pbr::OriginalName("WorldEventType_WorldEventTypePlayerReset")] WorldEventTypePlayerReset = 9,
    [pbr::OriginalName("WorldEventType_WorldEventTypeResetAreaState")] WorldEventTypeResetAreaState = 10,
    /// <summary>
    /// 环境
    /// </summary>
    [pbr::OriginalName("WorldEventType_WorldEventTypeDiurnalCycleChange")] WorldEventTypeDiurnalCycleChange = 30,
    /// <summary>
    /// chunk事件
    /// </summary>
    [pbr::OriginalName("WorldEventType_WorldEventTypeEntityEventCall")] WorldEventTypeEntityEventCall = 101,
    [pbr::OriginalName("WorldEventType_WorldEventTypeAddEntityToChunkGrid")] WorldEventTypeAddEntityToChunkGrid = 102,
    [pbr::OriginalName("WorldEventType_WorldEventTypeGetEntity")] WorldEventTypeGetEntity = 104,
    [pbr::OriginalName("WorldEventType_WorldEventTypeEntityEventCallNoReturn")] WorldEventTypeEntityEventCallNoReturn = 105,
    [pbr::OriginalName("WorldEventType_WorldEventTypeRestartAllEntitiesCodeBlock")] WorldEventTypeRestartAllEntitiesCodeBlock = 106,
    [pbr::OriginalName("WorldEventType_WorldEventTypeResourceLoadFinish")] WorldEventTypeResourceLoadFinish = 107,
    [pbr::OriginalName("WorldEventType_WorldEventTypeUpdateWidgetAttr")] WorldEventTypeUpdateWidgetAttr = 108,
    /// <summary>
    ///领地物件运行代码块事件
    /// </summary>
    [pbr::OriginalName("WorldEventType_WorldEventTypeRunCodeBlockByPlayerArea")] WorldEventTypeRunCodeBlockByPlayerArea = 109,
    [pbr::OriginalName("WorldEventType_WorldEventTypeEntitiesRestartCodeBlock")] WorldEventTypeEntitiesRestartCodeBlock = 110,
    /// <summary>
    ///公共领地所有实体重启代码块
    /// </summary>
    [pbr::OriginalName("WorldEventType_WorldEventTypePublicAreaRestartCode")] WorldEventTypePublicAreaRestartCode = 112,
    [pbr::OriginalName("WorldEventType_WorldEventTypePlayerAreaRestartCode")] WorldEventTypePlayerAreaRestartCode = 113,
    [pbr::OriginalName("WorldEventType_WorldEventTypeRemoveEntityChange")] WorldEventTypeRemoveEntityChange = 114,
    [pbr::OriginalName("WorldEventType_WorldEventTypeReviveEntity")] WorldEventTypeReviveEntity = 115,
    /// <summary>
    ///副本地图回溯 事件
    /// </summary>
    [pbr::OriginalName("WorldEventType_WorldEventTypeRestartDungeonMap")] WorldEventTypeRestartDungeonMap = 116,
    /// <summary>
    ///  触发实体的开始事件代码块
    /// </summary>
    [pbr::OriginalName("WorldEventType_WorldEventTypeEntitiesExecuteStartEvent")] WorldEventTypeEntitiesExecuteStartEvent = 117,
    /// <summary>
    /// 停止实体的所有代码块(重置到事件等待触发状态)
    /// </summary>
    [pbr::OriginalName("WorldEventType_WorldEventTypeEntitiesStopCodeBlock")] WorldEventTypeEntitiesStopCodeBlock = 118,
    /// <summary>
    /// 应用组件模板到实体
    /// </summary>
    [pbr::OriginalName("WorldEventType_WorldEventTypeApplyEntityTemplate")] WorldEventTypeApplyEntityTemplate = 120,
    [pbr::OriginalName("WorldEventType_WorldEventTypeAddCameraToChunkGrid")] WorldEventTypeAddCameraToChunkGrid = 121,
    /// <summary>
    /// 场景区域重新运行代码块
    /// </summary>
    [pbr::OriginalName("WorldEventType_WorldEventTypeZoneAreaRestartCode")] WorldEventTypeZoneAreaRestartCode = 122,
    [pbr::OriginalName("WorldEventType_WorldEventTypeAddEntityWithoutViewToChunkGrid")] WorldEventTypeAddEntityWithoutViewToChunkGrid = 123,
    [pbr::OriginalName("WorldEventType_WorldEventTypeCodeEventNotification")] WorldEventTypeCodeEventNotification = 124,
    [pbr::OriginalName("WorldEventType_WorldEventTypePublicAreaResetCodeBlock")] WorldEventTypePublicAreaResetCodeBlock = 125,
    /// <summary>
    /// 场景区域运行开始代码块
    /// </summary>
    [pbr::OriginalName("WorldEventType_WorldEventTypeEntitiesExecuteQuickCodeStartEvent")] WorldEventTypeEntitiesExecuteQuickCodeStartEvent = 126,
    /// <summary>
    /// 运行或停止区域中可编码实体的快速编码状态
    /// </summary>
    [pbr::OriginalName("WorldEventType_WorldEventTypeResetEntitiesQuickCodeState")] WorldEventTypeResetEntitiesQuickCodeState = 127,
    /// <summary>
    /// 区域所有多实体快速编码标签页信息
    /// </summary>
    [pbr::OriginalName("WorldEventType_WorldEventTypeEntitiesQuickCodeTabDatas")] WorldEventTypeEntitiesQuickCodeTabDatas = 128,
    /// <summary>
    /// grid 事件
    /// </summary>
    [pbr::OriginalName("WorldEventType_WorldEventTypeToGridEvent")] WorldEventTypeToGridEvent = 150,
    [pbr::OriginalName("WorldEventType_WorldEventTypeZoomEvent")] WorldEventTypeZoomEvent = 151,
    /// <summary>
    /// build
    /// </summary>
    [pbr::OriginalName("WorldEventType_WorldEventTypePlayerAddEntity")] WorldEventTypePlayerAddEntity = 201,
    [pbr::OriginalName("WorldEventType_WorldEventTypePlayerDelEntity")] WorldEventTypePlayerDelEntity = 202,
    [pbr::OriginalName("WorldEventType_WorldEventTypePlayerMoveEntity")] WorldEventTypePlayerMoveEntity = 203,
    [pbr::OriginalName("WorldEventType_WorldEventTypeBotAddEntity")] WorldEventTypeBotAddEntity = 204,
    [pbr::OriginalName("WorldEventType_WorldEventTypePlayerDelEntityByScene")] WorldEventTypePlayerDelEntityByScene = 205,
    [pbr::OriginalName("WorldEventType_WorldEventTypePlayerAddResourcePoint")] WorldEventTypePlayerAddResourcePoint = 210,
    [pbr::OriginalName("WorldEventType_WorldEventTypePlayerDelResourcePoint")] WorldEventTypePlayerDelResourcePoint = 211,
    [pbr::OriginalName("WorldEventType_WorldEventTypePlayerAddBornPoint")] WorldEventTypePlayerAddBornPoint = 212,
    [pbr::OriginalName("WorldEventType_WorldEventTypePlayerDelBornPoint")] WorldEventTypePlayerDelBornPoint = 213,
    /// <summary>
    ///s2z
    /// </summary>
    [pbr::OriginalName("WorldEventType_S2ZLessonAreaCreate")] S2ZlessonAreaCreate = 214,
    [pbr::OriginalName("WorldEventType_S2ZLessonAreaDel")] S2ZlessonAreaDel = 215,
    [pbr::OriginalName("WorldEventType_S2ZLessonAreaQuery")] S2ZlessonAreaQuery = 216,
    [pbr::OriginalName("WorldEventType_S2ZLessonAreaUpdate")] S2ZlessonAreaUpdate = 217,
    [pbr::OriginalName("WorldEventType_S2ZBeautyAreaUpdate")] S2ZbeautyAreaUpdate = 218,
    [pbr::OriginalName("WorldEventType_S2ZLessonAreaCopy")] S2ZlessonAreaCopy = 219,
    [pbr::OriginalName("WorldEventType_S2ZLessonAreaIndexUpdate")] S2ZlessonAreaIndexUpdate = 220,
    [pbr::OriginalName("WorldEventType_S2ZLessonAreaUnlock")] S2ZlessonAreaUnlock = 221,
    [pbr::OriginalName("WorldEventType_S2ZLessonPlayerArrivedArea")] S2ZlessonPlayerArrivedArea = 222,
    [pbr::OriginalName("WorldEventType_S2ZLessonAreaRunQuickCodeStart")] S2ZlessonAreaRunQuickCodeStart = 223,
    [pbr::OriginalName("WorldEventType_WorldEventTypeAddTileMapSign")] WorldEventTypeAddTileMapSign = 224,
    [pbr::OriginalName("WorldEventType_WorldEventTypeRemoveTileMapSign")] WorldEventTypeRemoveTileMapSign = 225,
    /// <summary>
    /// bot
    /// </summary>
    [pbr::OriginalName("WorldEventType_WorldEventTypeSpawnBot")] WorldEventTypeSpawnBot = 301,
    [pbr::OriginalName("WorldEventType_WorldEventTypeRecallBot")] WorldEventTypeRecallBot = 302,
    /// <summary>
    /// 功能实体事件
    /// </summary>
    [pbr::OriginalName("WorldEventType_WorldEventTypeIssueSettle")] WorldEventTypeIssueSettle = 401,
    [pbr::OriginalName("WorldEventType_WorldEventTypeGetEntityIssue")] WorldEventTypeGetEntityIssue = 402,
    /// <summary>
    ///工作台事件
    /// </summary>
    [pbr::OriginalName("WorldEventType_WorldEventTypeWorkbenchUpdateSub")] WorldEventTypeWorkbenchUpdateSub = 506,
    [pbr::OriginalName("WorldEventType_WorldEventTypeWorkbenchUpdateFather")] WorldEventTypeWorkbenchUpdateFather = 507,
    /// <summary>
    /// 玩家领地
    /// </summary>
    [pbr::OriginalName("WorldEventType_WorldEventTypeSpawnPalyerArea")] WorldEventTypeSpawnPalyerArea = 600,
    [pbr::OriginalName("WorldEventType_WorldEventTypeMovePalyerArea")] WorldEventTypeMovePalyerArea = 601,
    [pbr::OriginalName("WorldEventType_WorldEventTypeRemovePalyerArea")] WorldEventTypeRemovePalyerArea = 602,
    [pbr::OriginalName("WorldEventType_WorldEventTypeQueryMyPalyerArea")] WorldEventTypeQueryMyPalyerArea = 603,
    [pbr::OriginalName("WorldEventType_WorldEventTypeSetGlobalVar")] WorldEventTypeSetGlobalVar = 604,
    [pbr::OriginalName("WorldEventType_WorldEventTypeQueryPalyerAreas")] WorldEventTypeQueryPalyerAreas = 605,
    [pbr::OriginalName("WorldEventType_WorldEventTypeQueryPalyerAreaByRc")] WorldEventTypeQueryPalyerAreaByRc = 606,
    [pbr::OriginalName("WorldEventType_S2ZManorBuy")] S2ZmanorBuy = 610,
    [pbr::OriginalName("WorldEventType_S2ZManorBuyMarkSync")] S2ZmanorBuyMarkSync = 611,
    /// <summary>
    ///领地打包成模板
    /// </summary>
    [pbr::OriginalName("WorldEventType_S2ZManorTemplatePacket")] S2ZmanorTemplatePacket = 612,
    /// <summary>
    ///应用领地模
    /// </summary>
    [pbr::OriginalName("WorldEventType_S2ZManorTemplateUse")] S2ZmanorTemplateUse = 613,
    /// <summary>
    /// B端 老师重置公共领地
    /// </summary>
    [pbr::OriginalName("WorldEventType_WorldEventTypeTeacherResetPublicManor")] WorldEventTypeTeacherResetPublicManor = 614,
    /// <summary>
    /// 领取空领地
    /// </summary>
    [pbr::OriginalName("WorldEventType_WorldEventTypeCreatAreaByEmptyArea")] WorldEventTypeCreatAreaByEmptyArea = 615,
    /// <summary>
    /// 检测领地
    /// </summary>
    [pbr::OriginalName("WorldEventType_WorldEventTypeManorTemplateCheck")] WorldEventTypeManorTemplateCheck = 616,
    /// <summary>
    /// 广播
    /// </summary>
    [pbr::OriginalName("WorldEventType_WorldEventTypeAreaUpdateTemplate")] WorldEventTypeAreaUpdateTemplate = 617,
    /// <summary>
    /// 将地图数据加载到领地中
    /// </summary>
    [pbr::OriginalName("WorldEventType_S2ZPlayerAreaLoadManorMap")] S2ZplayerAreaLoadManorMap = 618,
    /// <summary>
    ///领地改变大小
    /// </summary>
    [pbr::OriginalName("WorldEventType_S2ZManorTemplateChangeSize")] S2ZmanorTemplateChangeSize = 619,
    /// <summary>
    /// 领地回收
    /// </summary>
    [pbr::OriginalName("WorldEventType_S2ZPlayerManorTakeBack")] S2ZplayerManorTakeBack = 620,
    /// <summary>
    /// 更新领地回收时间
    /// </summary>
    [pbr::OriginalName("WorldEventType_WorldEventTypeUpdateAreaRecoverTime")] WorldEventTypeUpdateAreaRecoverTime = 621,
    /// <summary>
    /// 撤销重做
    /// </summary>
    [pbr::OriginalName("WorldEventType_WorldEventTypeUndo")] WorldEventTypeUndo = 701,
    /// <summary>
    /// 重做
    /// </summary>
    [pbr::OriginalName("WorldEventType_WorldEventTypeRedo")] WorldEventTypeRedo = 702,
    /// <summary>
    ///--------------代码块事件   800 ~ 899   -----------------
    /// </summary>
    [pbr::OriginalName("WorldEventType_WorldEventTypeCodeblockAddEntity")] WorldEventTypeCodeblockAddEntity = 801,
    [pbr::OriginalName("WorldEventType_WorldEventTypeCodeblockDelEntity")] WorldEventTypeCodeblockDelEntity = 802,
    /// <summary>
    ///透传过来的客户端消息
    /// </summary>
    [pbr::OriginalName("WorldEventType_WorldEventTypeClientMsg")] WorldEventTypeClientMsg = 9801,
    /// <summary>
    /// gm 9901~9999
    /// </summary>
    [pbr::OriginalName("WorldEventType_WorldEventTypeGmAddEntity")] WorldEventTypeGmAddEntity = 9901,
    /// <summary>
    /// -------------------------------------------------------------------------
    /// 大世界event协议号 9000 - 10000
    /// -------------------------------------------------------------------------
    /// </summary>
    [pbr::OriginalName("WorldEventType_WorldEventTypePlayerAddBigWorldSystemArea")] WorldEventTypePlayerAddBigWorldSystemArea = 9000,
    [pbr::OriginalName("WorldEventType_WorldEventTypePlayerDelBigWorldSystemArea")] WorldEventTypePlayerDelBigWorldSystemArea = 9001,
    /// <summary>
    /// 最大事件数
    /// </summary>
    [pbr::OriginalName("WorldEventType_WorldEventTypeNumMax")] WorldEventTypeNumMax = 65535,
  }

  public enum GridEventType {
    /// <summary>
    /// 场景事件
    /// </summary>
    [pbr::OriginalName("GridEventType_GridEventTypeUnknown")] GridEventTypeUnknown = 0,
    [pbr::OriginalName("GridEventType_GridEventTypeEntityEvent")] GridEventTypeEntityEvent = 1,
  }

  public enum EntityEventType {
    /// <summary>
    /// 场景事件
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypeUnknown")] EntityEventTypeUnknown = 0,
    /// <summary>
    /// --------------- 玩家事件 ----------------------------
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypeMoveTo")] EntityEventTypeMoveTo = 1,
    [pbr::OriginalName("EntityEventType_EntityEventTypeUseSkill")] EntityEventTypeUseSkill = 2,
    /// <summary>
    /// 换装
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypeChangeAvatars")] EntityEventTypeChangeAvatars = 3,
    /// <summary>
    /// 玩家属性更新
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypeUpdateProfile")] EntityEventTypeUpdateProfile = 4,
    /// <summary>
    /// 玩家技能更新(skillId=0->当前没有技能)
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypeUpdateSkill")] EntityEventTypeUpdateSkill = 5,
    /// <summary>
    /// 玩家等级更新
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypeUpdateLevel")] EntityEventTypeUpdateLevel = 6,
    /// <summary>
    /// 玩家恢复hp(快速)
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypeRecoveryHp")] EntityEventTypeRecoveryHp = 7,
    /// <summary>
    /// 传送
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypeTeleport")] EntityEventTypeTeleport = 9,
    /// <summary>
    /// 拾取掉落物品
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypePickFalling")] EntityEventTypePickFalling = 11,
    /// <summary>
    /// 拾取掉落包裹(FallingBox)
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypePickBox")] EntityEventTypePickBox = 12,
    /// <summary>
    ///传送回家
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypeHomeTeleport")] EntityEventTypeHomeTeleport = 13,
    /// <summary>
    ///添加buff
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypeAddBuff")] EntityEventTypeAddBuff = 14,
    /// <summary>
    ///删除buff
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypeRemoveBuff")] EntityEventTypeRemoveBuff = 15,
    /// <summary>
    ///角色复活(客户端消息)
    ///EntityEventType_EntityEventTypeC2ZPlayerRelive = 17;
    ///角色复活(逻辑层检测完复活区域后发送给场景层)
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypePlayerRespawn")] EntityEventTypePlayerRespawn = 18,
    /// <summary>
    ///通知玩家开始共享机器人视野
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypePlayerShareBotViewStart")] EntityEventTypePlayerShareBotViewStart = 19,
    /// <summary>
    ///通知玩家停止共享机器人视野
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypePlayerShareBotViewStop")] EntityEventTypePlayerShareBotViewStop = 20,
    /// <summary>
    ///拾取包裹返回
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypeS2ZPickFallingBox")] EntityEventTypeS2ZpickFallingBox = 21,
    /// <summary>
    ///一键解卡
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypePlayerUnStuck")] EntityEventTypePlayerUnStuck = 23,
    /// <summary>
    ///进入上帝视角
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypeEnterGodView")] EntityEventTypeEnterGodView = 24,
    /// <summary>
    ///离开上帝视角
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypeLeaveGodView")] EntityEventTypeLeaveGodView = 25,
    /// <summary>
    ///tp实体并触发事件
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypeTeleportAndTrigger")] EntityEventTypeTeleportAndTrigger = 26,
    [pbr::OriginalName("EntityEventType_EntityEventTypeStartOrStop")] EntityEventTypeStartOrStop = 96,
    [pbr::OriginalName("EntityEventType_EntityEventTypeEnterIdeModel")] EntityEventTypeEnterIdeModel = 97,
    [pbr::OriginalName("EntityEventType_EntityEventTypeQuitIdeModel")] EntityEventTypeQuitIdeModel = 98,
    [pbr::OriginalName("EntityEventType_EntityEventTypeClientMsg")] EntityEventTypeClientMsg = 100,
    /// <summary>
    /// 按键输入事件
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypeInputByKeypress")] EntityEventTypeInputByKeypress = 110,
    /// <summary>
    /// 其他输入事件
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypeInputBySpecific")] EntityEventTypeInputBySpecific = 111,
    /// <summary>
    /// 实体使用物件
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypeUseItem")] EntityEventTypeUseItem = 112,
    /// <summary>
    /// 实体丢弃物件
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypeDropItem")] EntityEventTypeDropItem = 113,
    /// <summary>
    /// 更新玩家副本闯关信息
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypePlayerDungeonUpdate")] EntityEventTypePlayerDungeonUpdate = 114,
    /// <summary>
    /// 玩家完成答题（添加积分和执行后续代码块）
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypePlayerIssueSettle")] EntityEventTypePlayerIssueSettle = 115,
    /// <summary>
    /// 更新玩家视野
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypePlayerViewUp")] EntityEventTypePlayerViewUp = 116,
    /// <summary>
    /// 玩家镜头移动
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypeCameraMoveTo")] EntityEventTypeCameraMoveTo = 118,
    /// <summary>
    ///通知镜头是否使用摄像头视野
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypeCameraShareView")] EntityEventTypeCameraShareView = 119,
    /// <summary>
    ///通知玩家是否使用镜头视野
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypePlayerShareView")] EntityEventTypePlayerShareView = 120,
    /// <summary>
    ///客户端预览镜头
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypeCameraTypeChange")] EntityEventTypeCameraTypeChange = 121,
    /// <summary>
    ///预览镜头拉取视野
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypeCameraPullView")] EntityEventTypeCameraPullView = 122,
    /// <summary>
    /// 重置玩家
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypeResetPlayer")] EntityEventTypeResetPlayer = 125,
    /// <summary>
    /// 重置玩家实体锁定状态
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypeResetLockedEntity")] EntityEventTypeResetLockedEntity = 126,
    /// <summary>
    /// --------------- 代码块 200-399 ------------------------
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypeCodeMoveArrived")] EntityEventTypeCodeMoveArrived = 200,
    [pbr::OriginalName("EntityEventType_EntityEventTypeCodeEventCall")] EntityEventTypeCodeEventCall = 205,
    [pbr::OriginalName("EntityEventType_EntityEventTypeCodeOnComponentObject")] EntityEventTypeCodeOnComponentObject = 213,
    [pbr::OriginalName("EntityEventType_EntityEventTypeProgramSave")] EntityEventTypeProgramSave = 214,
    [pbr::OriginalName("EntityEventType_EntityEventTypeCodeScreenSave")] EntityEventTypeCodeScreenSave = 215,
    [pbr::OriginalName("EntityEventType_EntityEventTypeCodeRestart")] EntityEventTypeCodeRestart = 216,
    [pbr::OriginalName("EntityEventType_EntityEventTypeCodeOnEnergyEmpty")] EntityEventTypeCodeOnEnergyEmpty = 217,
    [pbr::OriginalName("EntityEventType_EntityEventTypeCodeOnCopyNew")] EntityEventTypeCodeOnCopyNew = 218,
    [pbr::OriginalName("EntityEventType_EntityEventTypeCodeOnCopyDel")] EntityEventTypeCodeOnCopyDel = 219,
    [pbr::OriginalName("EntityEventType_EntityEventTypeCodeQuestionReplay")] EntityEventTypeCodeQuestionReplay = 220,
    [pbr::OriginalName("EntityEventType_EntityEventTypeCodeExecuteStartEvent")] EntityEventTypeCodeExecuteStartEvent = 221,
    [pbr::OriginalName("EntityEventType_EntityEventTypeCodeStopCodeBlock")] EntityEventTypeCodeStopCodeBlock = 222,
    [pbr::OriginalName("EntityEventType_EntityEventTypeCodeEntityAdd")] EntityEventTypeCodeEntityAdd = 224,
    [pbr::OriginalName("EntityEventType_EntityEventTypeCodeOnEntityOverlap")] EntityEventTypeCodeOnEntityOverlap = 225,
    [pbr::OriginalName("EntityEventType_EntityEventTypeCodeOnStampede")] EntityEventTypeCodeOnStampede = 228,
    [pbr::OriginalName("EntityEventType_EntityEventTypeCodeOnStampedeEnd")] EntityEventTypeCodeOnStampedeEnd = 229,
    [pbr::OriginalName("EntityEventType_EntityEventTypeCodeSetCanStampede")] EntityEventTypeCodeSetCanStampede = 230,
    [pbr::OriginalName("EntityEventType_EntityEventTypeCodeSetCanOperate")] EntityEventTypeCodeSetCanOperate = 231,
    [pbr::OriginalName("EntityEventType_EntityEventTypeCodeOnByClicked")] EntityEventTypeCodeOnByClicked = 237,
    [pbr::OriginalName("EntityEventType_EntityEventTypeCodeOnEnterRoom")] EntityEventTypeCodeOnEnterRoom = 238,
    [pbr::OriginalName("EntityEventType_EntityEventTypeCodeCopyFatherDead")] EntityEventTypeCodeCopyFatherDead = 239,
    [pbr::OriginalName("EntityEventType_EntityEventTypeCodeEditTimeLine")] EntityEventTypeCodeEditTimeLine = 240,
    [pbr::OriginalName("EntityEventType_EntityEventTypeTimeLineShowText")] EntityEventTypeTimeLineShowText = 241,
    [pbr::OriginalName("EntityEventType_EntityEventTypeTimeLineMoveToPos")] EntityEventTypeTimeLineMoveToPos = 242,
    [pbr::OriginalName("EntityEventType_EntityEventTypeTimeLinePlayAudio")] EntityEventTypeTimeLinePlayAudio = 243,
    [pbr::OriginalName("EntityEventType_EntityEventTypeTimeLineShowSubtitle")] EntityEventTypeTimeLineShowSubtitle = 244,
    [pbr::OriginalName("EntityEventType_EntityEventTypeCodeCGVideoEnd")] EntityEventTypeCodeCgvideoEnd = 245,
    [pbr::OriginalName("EntityEventType_EntityEventTypeQuickCodeRestart")] EntityEventTypeQuickCodeRestart = 246,
    /// <summary>
    /// 隐藏实体
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypeHide")] EntityEventTypeHide = 247,
    [pbr::OriginalName("EntityEventType_EntityEventTypeCodeEventCodeNotification")] EntityEventTypeCodeEventCodeNotification = 355,
    [pbr::OriginalName("EntityEventType_EntityEventTypeCodeSetProfile")] EntityEventTypeCodeSetProfile = 357,
    [pbr::OriginalName("EntityEventType_EntityEventTypeCodeSettingPanel")] EntityEventTypeCodeSettingPanel = 358,
    [pbr::OriginalName("EntityEventType_EntityEventTypeCodeMissionEnd")] EntityEventTypeCodeMissionEnd = 359,
    [pbr::OriginalName("EntityEventType_EntityEventTypeClickOperateBubble")] EntityEventTypeClickOperateBubble = 360,
    [pbr::OriginalName("EntityEventType_EntityEventTypeCodeCameraAction")] EntityEventTypeCodeCameraAction = 361,
    [pbr::OriginalName("EntityEventType_EntityEventTypePopComplexDiglog")] EntityEventTypePopComplexDiglog = 362,
    [pbr::OriginalName("EntityEventType_EntityEventTypeCodeSetCarryClass")] EntityEventTypeCodeSetCarryClass = 363,
    /// <summary>
    /// --------------- 机器人 400-409 ----------------------------
    ///通知机器人开始共享机器人视野
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypeBotShareViewStart")] EntityEventTypeBotShareViewStart = 400,
    /// <summary>
    ///通知机器人停止共享机器人视野
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypeBotShareViewStop")] EntityEventTypeBotShareViewStop = 401,
    [pbr::OriginalName("EntityEventType_EntityEventTypeAddFuel")] EntityEventTypeAddFuel = 403,
    [pbr::OriginalName("EntityEventType_EntityEventTypeBotChangeSkin")] EntityEventTypeBotChangeSkin = 404,
    [pbr::OriginalName("EntityEventType_EntityEventTypeBotRename")] EntityEventTypeBotRename = 405,
    /// <summary>
    /// --------------- 建造 450-459 ------------------------------
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypeBuildingSwitch")] EntityEventTypeBuildingSwitch = 450,
    [pbr::OriginalName("EntityEventType_EntityEventTypeBuildingModePosUpdate")] EntityEventTypeBuildingModePosUpdate = 451,
    [pbr::OriginalName("EntityEventType_EntityEventTypeQuitBuildingStatus")] EntityEventTypeQuitBuildingStatus = 452,
    /// <summary>
    /// --------------- 建筑物和工作台 500~549 --------------------
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypeWorkbenchObjectUpdate")] EntityEventTypeWorkbenchObjectUpdate = 501,
    [pbr::OriginalName("EntityEventType_EntityEventTypeBuildingWidgetUpdate")] EntityEventTypeBuildingWidgetUpdate = 502,
    [pbr::OriginalName("EntityEventType_EntityEventTypeWorkbenchAddFuel")] EntityEventTypeWorkbenchAddFuel = 512,
    [pbr::OriginalName("EntityEventType_EntityEventTypeWorkbenchComponent")] EntityEventTypeWorkbenchComponent = 513,
    [pbr::OriginalName("EntityEventType_EntityEventTypeWorkbenchResetComponent")] EntityEventTypeWorkbenchResetComponent = 514,
    [pbr::OriginalName("EntityEventType_EntityEventTypeWorkbenchSetPrompt")] EntityEventTypeWorkbenchSetPrompt = 515,
    [pbr::OriginalName("EntityEventType_EntityEventTypeWorkbenchUpdateSub")] EntityEventTypeWorkbenchUpdateSub = 516,
    [pbr::OriginalName("EntityEventType_EntityEventTypeWorkbenchUpdateFather")] EntityEventTypeWorkbenchUpdateFather = 517,
    /// <summary>
    /// --------------- entity场景事件 600 ~ 699 -----------------
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypeEntityLock")] EntityEventTypeEntityLock = 600,
    [pbr::OriginalName("EntityEventType_EntityEventTypeEntityUnLock")] EntityEventTypeEntityUnLock = 601,
    [pbr::OriginalName("EntityEventType_EntityEventTypeRegisterEntityCodeEvent")] EntityEventTypeRegisterEntityCodeEvent = 602,
    [pbr::OriginalName("EntityEventType_EntityEventTypeDestroyEntityCodeEvent")] EntityEventTypeDestroyEntityCodeEvent = 603,
    [pbr::OriginalName("EntityEventType_EntityEventTypeBeClick")] EntityEventTypeBeClick = 604,
    [pbr::OriginalName("EntityEventType_EntityEventTypeUpdateAnimation")] EntityEventTypeUpdateAnimation = 605,
    [pbr::OriginalName("EntityEventType_EntityEventTypeBeOperated")] EntityEventTypeBeOperated = 606,
    [pbr::OriginalName("EntityEventType_EntityEventTypeEntityLockUpdate")] EntityEventTypeEntityLockUpdate = 607,
    [pbr::OriginalName("EntityEventType_EntityEventTypeUpdateAudio")] EntityEventTypeUpdateAudio = 608,
    [pbr::OriginalName("EntityEventType_EntityEventTypePlayerAddDiyAudio")] EntityEventTypePlayerAddDiyAudio = 609,
    [pbr::OriginalName("EntityEventType_EntityEventTypePlayerGetDiyAudio")] EntityEventTypePlayerGetDiyAudio = 610,
    [pbr::OriginalName("EntityEventType_EntityEventTypeUpdateUseEmoji")] EntityEventTypeUpdateUseEmoji = 611,
    [pbr::OriginalName("EntityEventType_EntityEventTypeApplyEntityTemplate")] EntityEventTypeApplyEntityTemplate = 612,
    [pbr::OriginalName("EntityEventType_EntityEventTypeUpdateMapTemplate")] EntityEventTypeUpdateMapTemplate = 613,
    [pbr::OriginalName("EntityEventType_EntityEventTypeMonsterLockPlayer")] EntityEventTypeMonsterLockPlayer = 614,
    [pbr::OriginalName("EntityEventType_EntityEventTypePlayerForceExitFight")] EntityEventTypePlayerForceExitFight = 615,
    /// <summary>
    /// --------------- 聊天 1000~1050 ---------------------------
    /// 附近chat 信息
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypeSendNearbyChat")] EntityEventTypeSendNearbyChat = 1000,
    [pbr::OriginalName("EntityEventType_EntityEventTypeSendNearToCodeEntitybyChat")] EntityEventTypeSendNearToCodeEntitybyChat = 1001,
    /// <summary>
    /// --------------- 事件号最大值 ---------------
    /// </summary>
    [pbr::OriginalName("EntityEventType_EntityEventTypeNumMax")] EntityEventTypeNumMax = 65535,
  }

  public enum EventCodeType {
    /// <summary>
    /// 指定实体的代码块事件
    /// </summary>
    [pbr::OriginalName("EventCodeType_EventCodeTypeUnknown")] EventCodeTypeUnknown = 0,
    /// <summary>
    /// 指定实体的代码块事件
    /// </summary>
    [pbr::OriginalName("EventCodeType_EventCodeTypeServer")] EventCodeTypeServer = 1,
    /// <summary>
    /// 不指定某个实体的代码块事件
    /// </summary>
    [pbr::OriginalName("EventCodeType_EventCodeTypeEntityEvent")] EventCodeTypeEntityEvent = 2,
    /// <summary>
    /// 接收实体发送的广播呼叫
    /// </summary>
    [pbr::OriginalName("EventCodeType_EventCodeTypeReceiveEventCall")] EventCodeTypeReceiveEventCall = 3,
    /// <summary>
    /// 某类型的实体的事件
    /// </summary>
    [pbr::OriginalName("EventCodeType_EventCodeTypeEntityType")] EventCodeTypeEntityType = 4,
  }

  public enum EntityCodeEventType {
    [pbr::OriginalName("EntityCodeEventType_EntityCodeEventTypeUnknown")] EntityCodeEventTypeUnknown = 0,
    /// <summary>
    /// 实体点击事件
    /// </summary>
    [pbr::OriginalName("EntityCodeEventType_EntityCodeEventTypeBeClicked")] EntityCodeEventTypeBeClicked = 101,
    /// <summary>
    /// 实体坐标变更
    /// </summary>
    [pbr::OriginalName("EntityCodeEventType_EntityCodeEventTypePosUpdate")] EntityCodeEventTypePosUpdate = 102,
    /// <summary>
    /// 实体被攻击
    /// </summary>
    [pbr::OriginalName("EntityCodeEventType_EntityCodeEventTypeBeAttack")] EntityCodeEventTypeBeAttack = 103,
    /// <summary>
    /// 实体攻击
    /// </summary>
    [pbr::OriginalName("EntityCodeEventType_EntityCodeEventTypeAttack")] EntityCodeEventTypeAttack = 104,
    /// <summary>
    /// 实体死亡
    /// </summary>
    [pbr::OriginalName("EntityCodeEventType_EntityCodeEventTypeDead")] EntityCodeEventTypeDead = 105,
    /// <summary>
    /// 实体被操作
    /// </summary>
    [pbr::OriginalName("EntityCodeEventType_EntityCodeEventTypeOnTouch")] EntityCodeEventTypeOnTouch = 106,
    /// <summary>
    /// 实体当前帧更新
    /// </summary>
    [pbr::OriginalName("EntityCodeEventType_EntityCodeEventTypeFrameUpdate")] EntityCodeEventTypeFrameUpdate = 107,
    /// <summary>
    /// 实体能源变更
    /// </summary>
    [pbr::OriginalName("EntityCodeEventType_EntityCodeEventTypeFuelUpdate")] EntityCodeEventTypeFuelUpdate = 108,
    /// <summary>
    /// 实体使用技能
    /// </summary>
    [pbr::OriginalName("EntityCodeEventType_EntityCodeEventTypeUseSkill")] EntityCodeEventTypeUseSkill = 109,
    /// <summary>
    /// 操作失效/生效
    /// </summary>
    [pbr::OriginalName("EntityCodeEventType_EntityCodeEventTypeCanOperate")] EntityCodeEventTypeCanOperate = 110,
    /// <summary>
    /// 镜像
    /// </summary>
    [pbr::OriginalName("EntityCodeEventType_EntityCodeEventTypeMirror")] EntityCodeEventTypeMirror = 112,
    /// <summary>
    /// 合成物品
    /// </summary>
    [pbr::OriginalName("EntityCodeEventType_EntityCodeEventTypeComponent")] EntityCodeEventTypeComponent = 113,
    /// <summary>
    /// 接收广播
    /// </summary>
    [pbr::OriginalName("EntityCodeEventType_EntityCodeEventTypeReceiveEventCall")] EntityCodeEventTypeReceiveEventCall = 114,
    /// <summary>
    /// 变量改变
    /// </summary>
    [pbr::OriginalName("EntityCodeEventType_EntityCodeEventTypeVarChange")] EntityCodeEventTypeVarChange = 115,
    /// <summary>
    /// 实体被实体踩踏
    /// </summary>
    [pbr::OriginalName("EntityCodeEventType_EntityCodeEventTypeEntityBeStampede")] EntityCodeEventTypeEntityBeStampede = 116,
    /// <summary>
    /// 实体被实体踩踏结束
    /// </summary>
    [pbr::OriginalName("EntityCodeEventType_EntityCodeEventTypeEntityOverBeStampede")] EntityCodeEventTypeEntityOverBeStampede = 117,
    /// <summary>
    /// 实体被建造 || 任意实体被建造
    /// </summary>
    [pbr::OriginalName("EntityCodeEventType_EntityCodeEventTypeOnBuild")] EntityCodeEventTypeOnBuild = 118,
    /// <summary>
    /// 实体进入房间
    /// </summary>
    [pbr::OriginalName("EntityCodeEventType_EntityCodeEventTypeEnterRoom")] EntityCodeEventTypeEnterRoom = 119,
    /// <summary>
    /// 输入事件
    /// </summary>
    [pbr::OriginalName("EntityCodeEventType_EntityCodeEventTypeInputKeyAction")] EntityCodeEventTypeInputKeyAction = 121,
    /// <summary>
    /// 按键事件
    /// </summary>
    [pbr::OriginalName("EntityCodeEventType_EntityCodeEventTypeKeypress")] EntityCodeEventTypeKeypress = 122,
    /// <summary>
    /// 实体使用物件
    /// </summary>
    [pbr::OriginalName("EntityCodeEventType_EntityCodeEventTypeUseItem")] EntityCodeEventTypeUseItem = 124,
    /// <summary>
    /// 实体丢弃物件
    /// </summary>
    [pbr::OriginalName("EntityCodeEventType_EntityCodeEventTypeDropItem")] EntityCodeEventTypeDropItem = 125,
    /// <summary>
    /// 实体拾取物件
    /// </summary>
    [pbr::OriginalName("EntityCodeEventType_EntityCodeEventTypePickupItem")] EntityCodeEventTypePickupItem = 126,
    /// <summary>
    /// 实体碰撞
    /// </summary>
    [pbr::OriginalName("EntityCodeEventType_EntityCodeEventTypeOnCrash")] EntityCodeEventTypeOnCrash = 129,
    /// <summary>
    /// 实体丢弃物件返回物品id
    /// </summary>
    [pbr::OriginalName("EntityCodeEventType_EntityCodeEventTypeDropItemWithId")] EntityCodeEventTypeDropItemWithId = 130,
    /// <summary>
    /// xx克隆体被删除
    /// </summary>
    [pbr::OriginalName("EntityCodeEventType_EntityCodeEventTypeOnCloneDel")] EntityCodeEventTypeOnCloneDel = 131,
    /// <summary>
    /// 实体被拿起
    /// </summary>
    [pbr::OriginalName("EntityCodeEventType_EntityEventTypeCodeOnBePickUp")] EntityEventTypeCodeOnBePickUp = 135,
    /// <summary>
    /// 实体被放下
    /// </summary>
    [pbr::OriginalName("EntityCodeEventType_EntityEventTypeCodeOnBePutDown")] EntityEventTypeCodeOnBePutDown = 136,
    /// <summary>
    /// 实体被销毁
    /// </summary>
    [pbr::OriginalName("EntityCodeEventType_EntityEventTypeCodeOnBeDestroy")] EntityEventTypeCodeOnBeDestroy = 137,
    /// <summary>
    /// 玩家完成答题
    /// </summary>
    [pbr::OriginalName("EntityCodeEventType_EntityEventTypeCodePlayerIssueSettle")] EntityEventTypeCodePlayerIssueSettle = 138,
    /// <summary>
    /// 当实体快速编码运行/停止时触发（需打开可编码属性生效）
    /// </summary>
    [pbr::OriginalName("EntityCodeEventType_EntityEventTypeEntitiesQuickCodeRunOrStop")] EntityEventTypeEntitiesQuickCodeRunOrStop = 139,
  }

  /// <summary>
  /// 数据保存事件TYPE
  /// </summary>
  public enum DataSaveType {
    [pbr::OriginalName("DataSaveType_DataSaveTypeUnknown")] DataSaveTypeUnknown = 0,
    [pbr::OriginalName("DataSaveType_DataSaveTypeMapGob")] DataSaveTypeMapGob = 1001,
  }

  /// <summary>
  /// 场景作用力消失时机
  /// </summary>
  public enum SceneForceRemoveTime {
    [pbr::OriginalName("SceneForceRemoveTime_SceneForceRemoveTimeUnknown")] SceneForceRemoveTimeUnknown = 0,
    /// <summary>
    /// 离开指定区域
    /// </summary>
    [pbr::OriginalName("SceneForceRemoveTime_SceneForceRemoveTimeLeave")] SceneForceRemoveTimeLeave = 2001,
    /// <summary>
    /// 到达指定目标点
    /// </summary>
    [pbr::OriginalName("SceneForceRemoveTime_SceneForceRemoveTimeTargetRC")] SceneForceRemoveTimeTargetRc = 2002,
    /// <summary>
    /// 持续多少时间
    /// </summary>
    [pbr::OriginalName("SceneForceRemoveTime_SceneForceRemoveTimeRunTime")] SceneForceRemoveTimeRunTime = 2003,
    /// <summary>
    /// 移动多少距离
    /// </summary>
    [pbr::OriginalName("SceneForceRemoveTime_SceneForceRemoveTimeDist")] SceneForceRemoveTimeDist = 2004,
  }

  #endregion

}

#endregion Designer generated code
