// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: task.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MelandGame3 {

  /// <summary>Holder for reflection information generated from task.proto</summary>
  public static partial class TaskReflection {

    #region Descriptor
    /// <summary>File descriptor for task.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TaskReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cgp0YXNrLnByb3RvEgtNZWxhbmRHYW1lMyI/Cg5UYXNrT3B0aW9uSXRlbRIQ",
            "CghpdGVtX2NpZBgBIAEoBRILCgNudW0YAiABKAUSDgoGbmZ0X2lkGAMgASgJ",
            "IjEKEVRhc2tPcHRpb25Nb25zdGVyEg8KB21vbl9jaWQYASABKAUSCwoDbnVt",
            "GAIgASgFIigKEFRhc2tPcHRpb25Nb3ZlVG8SCQoBchgBIAEoBRIJCgFjGAIg",
            "ASgFIjUKDlRhc2tPcHRpb25RdWl6EhEKCXF1aXpfdHlwZRgBIAEoBRIQCghx",
            "dWl6X251bRgCIAEoBSKQAgoNVGFza09wdGlvbkNuZhIjCgRraW5kGAEgASgO",
            "MhUuTWVsYW5kR2FtZTMuVGFza1R5cGUSDQoDbnVtGAsgASgFSAASKwoEaXRl",
            "bRgMIAEoCzIbLk1lbGFuZEdhbWUzLlRhc2tPcHRpb25JdGVtSAASMgoIbW9u",
            "X2luZm8YDSABKAsyHi5NZWxhbmRHYW1lMy5UYXNrT3B0aW9uTW9uc3RlckgA",
            "EjAKB3Rhcl9wb3MYDiABKAsyHS5NZWxhbmRHYW1lMy5UYXNrT3B0aW9uTW92",
            "ZVRvSAASMAoJcXVpel9pbmZvGA8gASgLMhsuTWVsYW5kR2FtZTMuVGFza09w",
            "dGlvblF1aXpIAEIGCgRkYXRhIkoKClRhc2tPcHRpb24SLgoKb3B0aW9uX2Nu",
            "ZhgBIAEoCzIaLk1lbGFuZEdhbWUzLlRhc2tPcHRpb25DbmYSDAoEcmF0ZRgC",
            "IAEoBSKDAQoEVGFzaxIPCgd0YXNrX2lkGAEgASgFEigKCXRhc2tfa2luZBgC",
            "IAEoDjIVLk1lbGFuZEdhbWUzLlRhc2tUeXBlEhYKDmNyZWF0ZWRfYXRfc2Vj",
            "GAMgASgDEigKB29wdGlvbnMYBCADKAsyFy5NZWxhbmRHYW1lMy5UYXNrT3B0",
            "aW9uIq4BCghUYXNrTGlzdBIKCgJpZBgBIAEoBRInCgRraW5kGAIgASgOMhku",
            "TWVsYW5kR2FtZTMuVGFza0xpc3RUeXBlEhMKC2Nhbl9yZWNlaXZlGAMgASgI",
            "Eg0KBWRvaW5nGAQgASgIEgwKBHJhdGUYBSABKAUSIwoIY3VyX3Rhc2sYBiAB",
            "KAsyES5NZWxhbmRHYW1lMy5UYXNrEhYKDnJlY2VpdmVfcmV3YXJkGAcgASgF",
            "IjcKClBsYXllclRhc2sSKQoKdGFza19saXN0cxgBIAMoCzIVLk1lbGFuZEdh",
            "bWUzLlRhc2tMaXN0KuEBCghUYXNrVHlwZRIcChhUYXNrVHlwZV9UYXNrVHlw",
            "ZVVua25vd24QABIcChhUYXNrVHlwZV9UYXNrVHlwZUdldEl0ZW0QARIcChhU",
            "YXNrVHlwZV9UYXNrVHlwZVVzZUl0ZW0QAhIgChxUYXNrVHlwZV9UYXNrVHlw",
            "ZUtpbGxNb25zdGVyEAMSGwoXVGFza1R5cGVfVGFza1R5cGVNb3ZlVG8QBBIZ",
            "ChVUYXNrVHlwZV9UYXNrVHlwZVF1aXoQBRIhCh1UYXNrVHlwZV9UYXNrVHlw",
            "ZU9jY3VwaWVkTGFuZBAGKqMBCgxUYXNrTGlzdFR5cGUSJAogVGFza0xpc3RU",
            "eXBlX1Rhc2tMaXN0VHlwZVVua25vd24QABIiCh5UYXNrTGlzdFR5cGVfVGFz",
            "a0xpc3RUeXBlRGFpbHkQARIlCiFUYXNrTGlzdFR5cGVfVGFza0xpc3RUeXBl",
            "UmV3YXJkZWQQAhIiCh5UYXNrTGlzdFR5cGVfVGFza0xpc3RUeXBlT3RoZXIQ",
            "A2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::MelandGame3.TaskType), typeof(global::MelandGame3.TaskListType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::MelandGame3.TaskOptionItem), global::MelandGame3.TaskOptionItem.Parser, new[]{ "ItemCid", "Num", "NftId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::MelandGame3.TaskOptionMonster), global::MelandGame3.TaskOptionMonster.Parser, new[]{ "MonCid", "Num" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::MelandGame3.TaskOptionMoveTo), global::MelandGame3.TaskOptionMoveTo.Parser, new[]{ "R", "C" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::MelandGame3.TaskOptionQuiz), global::MelandGame3.TaskOptionQuiz.Parser, new[]{ "QuizType", "QuizNum" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::MelandGame3.TaskOptionCnf), global::MelandGame3.TaskOptionCnf.Parser, new[]{ "Kind", "Num", "Item", "MonInfo", "TarPos", "QuizInfo" }, new[]{ "Data" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::MelandGame3.TaskOption), global::MelandGame3.TaskOption.Parser, new[]{ "OptionCnf", "Rate" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::MelandGame3.Task), global::MelandGame3.Task.Parser, new[]{ "TaskId", "TaskKind", "CreatedAtSec", "Options" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::MelandGame3.TaskList), global::MelandGame3.TaskList.Parser, new[]{ "Id", "Kind", "CanReceive", "Doing", "Rate", "CurTask", "ReceiveReward" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::MelandGame3.PlayerTask), global::MelandGame3.PlayerTask.Parser, new[]{ "TaskLists" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum TaskType {
    [pbr::OriginalName("TaskType_TaskTypeUnknown")] TaskTypeUnknown = 0,
    /// <summary>
    /// 寻物任务
    /// </summary>
    [pbr::OriginalName("TaskType_TaskTypeGetItem")] TaskTypeGetItem = 1,
    /// <summary>
    /// 使用道具
    /// </summary>
    [pbr::OriginalName("TaskType_TaskTypeUseItem")] TaskTypeUseItem = 2,
    /// <summary>
    /// 打怪任务
    /// </summary>
    [pbr::OriginalName("TaskType_TaskTypeKillMonster")] TaskTypeKillMonster = 3,
    /// <summary>
    /// 寻路任务
    /// </summary>
    [pbr::OriginalName("TaskType_TaskTypeMoveTo")] TaskTypeMoveTo = 4,
    /// <summary>
    /// Quiz
    /// </summary>
    [pbr::OriginalName("TaskType_TaskTypeQuiz")] TaskTypeQuiz = 5,
    /// <summary>
    /// 攻占地块
    /// </summary>
    [pbr::OriginalName("TaskType_TaskTypeOccupiedLand")] TaskTypeOccupiedLand = 6,
  }

  public enum TaskListType {
    [pbr::OriginalName("TaskListType_TaskListTypeUnknown")] TaskListTypeUnknown = 0,
    /// <summary>
    /// 每日任务
    /// </summary>
    [pbr::OriginalName("TaskListType_TaskListTypeDaily")] TaskListTypeDaily = 1,
    /// <summary>
    /// 悬赏任务
    /// </summary>
    [pbr::OriginalName("TaskListType_TaskListTypeRewarded")] TaskListTypeRewarded = 2,
    /// <summary>
    /// other任务
    /// </summary>
    [pbr::OriginalName("TaskListType_TaskListTypeOther")] TaskListTypeOther = 3,
  }

  #endregion

  #region Messages
  public sealed partial class TaskOptionItem : pb::IMessage<TaskOptionItem>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TaskOptionItem> _parser = new pb::MessageParser<TaskOptionItem>(() => new TaskOptionItem());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TaskOptionItem> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MelandGame3.TaskReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TaskOptionItem() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TaskOptionItem(TaskOptionItem other) : this() {
      itemCid_ = other.itemCid_;
      num_ = other.num_;
      nftId_ = other.nftId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TaskOptionItem Clone() {
      return new TaskOptionItem(this);
    }

    /// <summary>Field number for the "item_cid" field.</summary>
    public const int ItemCidFieldNumber = 1;
    private int itemCid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ItemCid {
      get { return itemCid_; }
      set {
        itemCid_ = value;
      }
    }

    /// <summary>Field number for the "num" field.</summary>
    public const int NumFieldNumber = 2;
    private int num_;
    /// <summary>
    /// max 10
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Num {
      get { return num_; }
      set {
        num_ = value;
      }
    }

    /// <summary>Field number for the "nft_id" field.</summary>
    public const int NftIdFieldNumber = 3;
    private string nftId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string NftId {
      get { return nftId_; }
      set {
        nftId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TaskOptionItem);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TaskOptionItem other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ItemCid != other.ItemCid) return false;
      if (Num != other.Num) return false;
      if (NftId != other.NftId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ItemCid != 0) hash ^= ItemCid.GetHashCode();
      if (Num != 0) hash ^= Num.GetHashCode();
      if (NftId.Length != 0) hash ^= NftId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ItemCid != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ItemCid);
      }
      if (Num != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Num);
      }
      if (NftId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(NftId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ItemCid != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ItemCid);
      }
      if (Num != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Num);
      }
      if (NftId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(NftId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ItemCid != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ItemCid);
      }
      if (Num != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Num);
      }
      if (NftId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NftId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TaskOptionItem other) {
      if (other == null) {
        return;
      }
      if (other.ItemCid != 0) {
        ItemCid = other.ItemCid;
      }
      if (other.Num != 0) {
        Num = other.Num;
      }
      if (other.NftId.Length != 0) {
        NftId = other.NftId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ItemCid = input.ReadInt32();
            break;
          }
          case 16: {
            Num = input.ReadInt32();
            break;
          }
          case 26: {
            NftId = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ItemCid = input.ReadInt32();
            break;
          }
          case 16: {
            Num = input.ReadInt32();
            break;
          }
          case 26: {
            NftId = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class TaskOptionMonster : pb::IMessage<TaskOptionMonster>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TaskOptionMonster> _parser = new pb::MessageParser<TaskOptionMonster>(() => new TaskOptionMonster());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TaskOptionMonster> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MelandGame3.TaskReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TaskOptionMonster() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TaskOptionMonster(TaskOptionMonster other) : this() {
      monCid_ = other.monCid_;
      num_ = other.num_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TaskOptionMonster Clone() {
      return new TaskOptionMonster(this);
    }

    /// <summary>Field number for the "mon_cid" field.</summary>
    public const int MonCidFieldNumber = 1;
    private int monCid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int MonCid {
      get { return monCid_; }
      set {
        monCid_ = value;
      }
    }

    /// <summary>Field number for the "num" field.</summary>
    public const int NumFieldNumber = 2;
    private int num_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Num {
      get { return num_; }
      set {
        num_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TaskOptionMonster);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TaskOptionMonster other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MonCid != other.MonCid) return false;
      if (Num != other.Num) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (MonCid != 0) hash ^= MonCid.GetHashCode();
      if (Num != 0) hash ^= Num.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MonCid != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(MonCid);
      }
      if (Num != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Num);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MonCid != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(MonCid);
      }
      if (Num != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Num);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (MonCid != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MonCid);
      }
      if (Num != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Num);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TaskOptionMonster other) {
      if (other == null) {
        return;
      }
      if (other.MonCid != 0) {
        MonCid = other.MonCid;
      }
      if (other.Num != 0) {
        Num = other.Num;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            MonCid = input.ReadInt32();
            break;
          }
          case 16: {
            Num = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            MonCid = input.ReadInt32();
            break;
          }
          case 16: {
            Num = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class TaskOptionMoveTo : pb::IMessage<TaskOptionMoveTo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TaskOptionMoveTo> _parser = new pb::MessageParser<TaskOptionMoveTo>(() => new TaskOptionMoveTo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TaskOptionMoveTo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MelandGame3.TaskReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TaskOptionMoveTo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TaskOptionMoveTo(TaskOptionMoveTo other) : this() {
      r_ = other.r_;
      c_ = other.c_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TaskOptionMoveTo Clone() {
      return new TaskOptionMoveTo(this);
    }

    /// <summary>Field number for the "r" field.</summary>
    public const int RFieldNumber = 1;
    private int r_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int R {
      get { return r_; }
      set {
        r_ = value;
      }
    }

    /// <summary>Field number for the "c" field.</summary>
    public const int CFieldNumber = 2;
    private int c_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int C {
      get { return c_; }
      set {
        c_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TaskOptionMoveTo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TaskOptionMoveTo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (R != other.R) return false;
      if (C != other.C) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (R != 0) hash ^= R.GetHashCode();
      if (C != 0) hash ^= C.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (R != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(R);
      }
      if (C != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(C);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (R != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(R);
      }
      if (C != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(C);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (R != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(R);
      }
      if (C != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(C);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TaskOptionMoveTo other) {
      if (other == null) {
        return;
      }
      if (other.R != 0) {
        R = other.R;
      }
      if (other.C != 0) {
        C = other.C;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            R = input.ReadInt32();
            break;
          }
          case 16: {
            C = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            R = input.ReadInt32();
            break;
          }
          case 16: {
            C = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class TaskOptionQuiz : pb::IMessage<TaskOptionQuiz>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TaskOptionQuiz> _parser = new pb::MessageParser<TaskOptionQuiz>(() => new TaskOptionQuiz());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TaskOptionQuiz> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MelandGame3.TaskReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TaskOptionQuiz() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TaskOptionQuiz(TaskOptionQuiz other) : this() {
      quizType_ = other.quizType_;
      quizNum_ = other.quizNum_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TaskOptionQuiz Clone() {
      return new TaskOptionQuiz(this);
    }

    /// <summary>Field number for the "quiz_type" field.</summary>
    public const int QuizTypeFieldNumber = 1;
    private int quizType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int QuizType {
      get { return quizType_; }
      set {
        quizType_ = value;
      }
    }

    /// <summary>Field number for the "quiz_num" field.</summary>
    public const int QuizNumFieldNumber = 2;
    private int quizNum_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int QuizNum {
      get { return quizNum_; }
      set {
        quizNum_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TaskOptionQuiz);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TaskOptionQuiz other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (QuizType != other.QuizType) return false;
      if (QuizNum != other.QuizNum) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (QuizType != 0) hash ^= QuizType.GetHashCode();
      if (QuizNum != 0) hash ^= QuizNum.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (QuizType != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(QuizType);
      }
      if (QuizNum != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(QuizNum);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (QuizType != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(QuizType);
      }
      if (QuizNum != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(QuizNum);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (QuizType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(QuizType);
      }
      if (QuizNum != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(QuizNum);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TaskOptionQuiz other) {
      if (other == null) {
        return;
      }
      if (other.QuizType != 0) {
        QuizType = other.QuizType;
      }
      if (other.QuizNum != 0) {
        QuizNum = other.QuizNum;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            QuizType = input.ReadInt32();
            break;
          }
          case 16: {
            QuizNum = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            QuizType = input.ReadInt32();
            break;
          }
          case 16: {
            QuizNum = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class TaskOptionCnf : pb::IMessage<TaskOptionCnf>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TaskOptionCnf> _parser = new pb::MessageParser<TaskOptionCnf>(() => new TaskOptionCnf());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TaskOptionCnf> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MelandGame3.TaskReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TaskOptionCnf() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TaskOptionCnf(TaskOptionCnf other) : this() {
      kind_ = other.kind_;
      switch (other.DataCase) {
        case DataOneofCase.Num:
          Num = other.Num;
          break;
        case DataOneofCase.Item:
          Item = other.Item.Clone();
          break;
        case DataOneofCase.MonInfo:
          MonInfo = other.MonInfo.Clone();
          break;
        case DataOneofCase.TarPos:
          TarPos = other.TarPos.Clone();
          break;
        case DataOneofCase.QuizInfo:
          QuizInfo = other.QuizInfo.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TaskOptionCnf Clone() {
      return new TaskOptionCnf(this);
    }

    /// <summary>Field number for the "kind" field.</summary>
    public const int KindFieldNumber = 1;
    private global::MelandGame3.TaskType kind_ = global::MelandGame3.TaskType.TaskTypeUnknown;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::MelandGame3.TaskType Kind {
      get { return kind_; }
      set {
        kind_ = value;
      }
    }

    /// <summary>Field number for the "num" field.</summary>
    public const int NumFieldNumber = 11;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Num {
      get { return dataCase_ == DataOneofCase.Num ? (int) data_ : 0; }
      set {
        data_ = value;
        dataCase_ = DataOneofCase.Num;
      }
    }

    /// <summary>Field number for the "item" field.</summary>
    public const int ItemFieldNumber = 12;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::MelandGame3.TaskOptionItem Item {
      get { return dataCase_ == DataOneofCase.Item ? (global::MelandGame3.TaskOptionItem) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.Item;
      }
    }

    /// <summary>Field number for the "mon_info" field.</summary>
    public const int MonInfoFieldNumber = 13;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::MelandGame3.TaskOptionMonster MonInfo {
      get { return dataCase_ == DataOneofCase.MonInfo ? (global::MelandGame3.TaskOptionMonster) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.MonInfo;
      }
    }

    /// <summary>Field number for the "tar_pos" field.</summary>
    public const int TarPosFieldNumber = 14;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::MelandGame3.TaskOptionMoveTo TarPos {
      get { return dataCase_ == DataOneofCase.TarPos ? (global::MelandGame3.TaskOptionMoveTo) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.TarPos;
      }
    }

    /// <summary>Field number for the "quiz_info" field.</summary>
    public const int QuizInfoFieldNumber = 15;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::MelandGame3.TaskOptionQuiz QuizInfo {
      get { return dataCase_ == DataOneofCase.QuizInfo ? (global::MelandGame3.TaskOptionQuiz) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.QuizInfo;
      }
    }

    private object data_;
    /// <summary>Enum of possible cases for the "data" oneof.</summary>
    public enum DataOneofCase {
      None = 0,
      Num = 11,
      Item = 12,
      MonInfo = 13,
      TarPos = 14,
      QuizInfo = 15,
    }
    private DataOneofCase dataCase_ = DataOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DataOneofCase DataCase {
      get { return dataCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearData() {
      dataCase_ = DataOneofCase.None;
      data_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TaskOptionCnf);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TaskOptionCnf other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Kind != other.Kind) return false;
      if (Num != other.Num) return false;
      if (!object.Equals(Item, other.Item)) return false;
      if (!object.Equals(MonInfo, other.MonInfo)) return false;
      if (!object.Equals(TarPos, other.TarPos)) return false;
      if (!object.Equals(QuizInfo, other.QuizInfo)) return false;
      if (DataCase != other.DataCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Kind != global::MelandGame3.TaskType.TaskTypeUnknown) hash ^= Kind.GetHashCode();
      if (dataCase_ == DataOneofCase.Num) hash ^= Num.GetHashCode();
      if (dataCase_ == DataOneofCase.Item) hash ^= Item.GetHashCode();
      if (dataCase_ == DataOneofCase.MonInfo) hash ^= MonInfo.GetHashCode();
      if (dataCase_ == DataOneofCase.TarPos) hash ^= TarPos.GetHashCode();
      if (dataCase_ == DataOneofCase.QuizInfo) hash ^= QuizInfo.GetHashCode();
      hash ^= (int) dataCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Kind != global::MelandGame3.TaskType.TaskTypeUnknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Kind);
      }
      if (dataCase_ == DataOneofCase.Num) {
        output.WriteRawTag(88);
        output.WriteInt32(Num);
      }
      if (dataCase_ == DataOneofCase.Item) {
        output.WriteRawTag(98);
        output.WriteMessage(Item);
      }
      if (dataCase_ == DataOneofCase.MonInfo) {
        output.WriteRawTag(106);
        output.WriteMessage(MonInfo);
      }
      if (dataCase_ == DataOneofCase.TarPos) {
        output.WriteRawTag(114);
        output.WriteMessage(TarPos);
      }
      if (dataCase_ == DataOneofCase.QuizInfo) {
        output.WriteRawTag(122);
        output.WriteMessage(QuizInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Kind != global::MelandGame3.TaskType.TaskTypeUnknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Kind);
      }
      if (dataCase_ == DataOneofCase.Num) {
        output.WriteRawTag(88);
        output.WriteInt32(Num);
      }
      if (dataCase_ == DataOneofCase.Item) {
        output.WriteRawTag(98);
        output.WriteMessage(Item);
      }
      if (dataCase_ == DataOneofCase.MonInfo) {
        output.WriteRawTag(106);
        output.WriteMessage(MonInfo);
      }
      if (dataCase_ == DataOneofCase.TarPos) {
        output.WriteRawTag(114);
        output.WriteMessage(TarPos);
      }
      if (dataCase_ == DataOneofCase.QuizInfo) {
        output.WriteRawTag(122);
        output.WriteMessage(QuizInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Kind != global::MelandGame3.TaskType.TaskTypeUnknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Kind);
      }
      if (dataCase_ == DataOneofCase.Num) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Num);
      }
      if (dataCase_ == DataOneofCase.Item) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Item);
      }
      if (dataCase_ == DataOneofCase.MonInfo) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MonInfo);
      }
      if (dataCase_ == DataOneofCase.TarPos) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TarPos);
      }
      if (dataCase_ == DataOneofCase.QuizInfo) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(QuizInfo);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TaskOptionCnf other) {
      if (other == null) {
        return;
      }
      if (other.Kind != global::MelandGame3.TaskType.TaskTypeUnknown) {
        Kind = other.Kind;
      }
      switch (other.DataCase) {
        case DataOneofCase.Num:
          Num = other.Num;
          break;
        case DataOneofCase.Item:
          if (Item == null) {
            Item = new global::MelandGame3.TaskOptionItem();
          }
          Item.MergeFrom(other.Item);
          break;
        case DataOneofCase.MonInfo:
          if (MonInfo == null) {
            MonInfo = new global::MelandGame3.TaskOptionMonster();
          }
          MonInfo.MergeFrom(other.MonInfo);
          break;
        case DataOneofCase.TarPos:
          if (TarPos == null) {
            TarPos = new global::MelandGame3.TaskOptionMoveTo();
          }
          TarPos.MergeFrom(other.TarPos);
          break;
        case DataOneofCase.QuizInfo:
          if (QuizInfo == null) {
            QuizInfo = new global::MelandGame3.TaskOptionQuiz();
          }
          QuizInfo.MergeFrom(other.QuizInfo);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Kind = (global::MelandGame3.TaskType) input.ReadEnum();
            break;
          }
          case 88: {
            Num = input.ReadInt32();
            break;
          }
          case 98: {
            global::MelandGame3.TaskOptionItem subBuilder = new global::MelandGame3.TaskOptionItem();
            if (dataCase_ == DataOneofCase.Item) {
              subBuilder.MergeFrom(Item);
            }
            input.ReadMessage(subBuilder);
            Item = subBuilder;
            break;
          }
          case 106: {
            global::MelandGame3.TaskOptionMonster subBuilder = new global::MelandGame3.TaskOptionMonster();
            if (dataCase_ == DataOneofCase.MonInfo) {
              subBuilder.MergeFrom(MonInfo);
            }
            input.ReadMessage(subBuilder);
            MonInfo = subBuilder;
            break;
          }
          case 114: {
            global::MelandGame3.TaskOptionMoveTo subBuilder = new global::MelandGame3.TaskOptionMoveTo();
            if (dataCase_ == DataOneofCase.TarPos) {
              subBuilder.MergeFrom(TarPos);
            }
            input.ReadMessage(subBuilder);
            TarPos = subBuilder;
            break;
          }
          case 122: {
            global::MelandGame3.TaskOptionQuiz subBuilder = new global::MelandGame3.TaskOptionQuiz();
            if (dataCase_ == DataOneofCase.QuizInfo) {
              subBuilder.MergeFrom(QuizInfo);
            }
            input.ReadMessage(subBuilder);
            QuizInfo = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Kind = (global::MelandGame3.TaskType) input.ReadEnum();
            break;
          }
          case 88: {
            Num = input.ReadInt32();
            break;
          }
          case 98: {
            global::MelandGame3.TaskOptionItem subBuilder = new global::MelandGame3.TaskOptionItem();
            if (dataCase_ == DataOneofCase.Item) {
              subBuilder.MergeFrom(Item);
            }
            input.ReadMessage(subBuilder);
            Item = subBuilder;
            break;
          }
          case 106: {
            global::MelandGame3.TaskOptionMonster subBuilder = new global::MelandGame3.TaskOptionMonster();
            if (dataCase_ == DataOneofCase.MonInfo) {
              subBuilder.MergeFrom(MonInfo);
            }
            input.ReadMessage(subBuilder);
            MonInfo = subBuilder;
            break;
          }
          case 114: {
            global::MelandGame3.TaskOptionMoveTo subBuilder = new global::MelandGame3.TaskOptionMoveTo();
            if (dataCase_ == DataOneofCase.TarPos) {
              subBuilder.MergeFrom(TarPos);
            }
            input.ReadMessage(subBuilder);
            TarPos = subBuilder;
            break;
          }
          case 122: {
            global::MelandGame3.TaskOptionQuiz subBuilder = new global::MelandGame3.TaskOptionQuiz();
            if (dataCase_ == DataOneofCase.QuizInfo) {
              subBuilder.MergeFrom(QuizInfo);
            }
            input.ReadMessage(subBuilder);
            QuizInfo = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class TaskOption : pb::IMessage<TaskOption>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TaskOption> _parser = new pb::MessageParser<TaskOption>(() => new TaskOption());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TaskOption> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MelandGame3.TaskReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TaskOption() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TaskOption(TaskOption other) : this() {
      optionCnf_ = other.optionCnf_ != null ? other.optionCnf_.Clone() : null;
      rate_ = other.rate_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TaskOption Clone() {
      return new TaskOption(this);
    }

    /// <summary>Field number for the "option_cnf" field.</summary>
    public const int OptionCnfFieldNumber = 1;
    private global::MelandGame3.TaskOptionCnf optionCnf_;
    /// <summary>
    /// 配置
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::MelandGame3.TaskOptionCnf OptionCnf {
      get { return optionCnf_; }
      set {
        optionCnf_ = value;
      }
    }

    /// <summary>Field number for the "rate" field.</summary>
    public const int RateFieldNumber = 2;
    private int rate_;
    /// <summary>
    /// 进度
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Rate {
      get { return rate_; }
      set {
        rate_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TaskOption);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TaskOption other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(OptionCnf, other.OptionCnf)) return false;
      if (Rate != other.Rate) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (optionCnf_ != null) hash ^= OptionCnf.GetHashCode();
      if (Rate != 0) hash ^= Rate.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (optionCnf_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(OptionCnf);
      }
      if (Rate != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Rate);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (optionCnf_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(OptionCnf);
      }
      if (Rate != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Rate);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (optionCnf_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(OptionCnf);
      }
      if (Rate != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Rate);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TaskOption other) {
      if (other == null) {
        return;
      }
      if (other.optionCnf_ != null) {
        if (optionCnf_ == null) {
          OptionCnf = new global::MelandGame3.TaskOptionCnf();
        }
        OptionCnf.MergeFrom(other.OptionCnf);
      }
      if (other.Rate != 0) {
        Rate = other.Rate;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (optionCnf_ == null) {
              OptionCnf = new global::MelandGame3.TaskOptionCnf();
            }
            input.ReadMessage(OptionCnf);
            break;
          }
          case 16: {
            Rate = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (optionCnf_ == null) {
              OptionCnf = new global::MelandGame3.TaskOptionCnf();
            }
            input.ReadMessage(OptionCnf);
            break;
          }
          case 16: {
            Rate = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// 任务
  /// </summary>
  public sealed partial class Task : pb::IMessage<Task>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Task> _parser = new pb::MessageParser<Task>(() => new Task());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Task> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MelandGame3.TaskReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Task() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Task(Task other) : this() {
      taskId_ = other.taskId_;
      taskKind_ = other.taskKind_;
      createdAtSec_ = other.createdAtSec_;
      options_ = other.options_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Task Clone() {
      return new Task(this);
    }

    /// <summary>Field number for the "task_id" field.</summary>
    public const int TaskIdFieldNumber = 1;
    private int taskId_;
    /// <summary>
    /// 任务 ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int TaskId {
      get { return taskId_; }
      set {
        taskId_ = value;
      }
    }

    /// <summary>Field number for the "task_kind" field.</summary>
    public const int TaskKindFieldNumber = 2;
    private global::MelandGame3.TaskType taskKind_ = global::MelandGame3.TaskType.TaskTypeUnknown;
    /// <summary>
    /// 任务类型
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::MelandGame3.TaskType TaskKind {
      get { return taskKind_; }
      set {
        taskKind_ = value;
      }
    }

    /// <summary>Field number for the "created_at_sec" field.</summary>
    public const int CreatedAtSecFieldNumber = 3;
    private long createdAtSec_;
    /// <summary>
    /// 任务的接取时间
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long CreatedAtSec {
      get { return createdAtSec_; }
      set {
        createdAtSec_ = value;
      }
    }

    /// <summary>Field number for the "options" field.</summary>
    public const int OptionsFieldNumber = 4;
    private static readonly pb::FieldCodec<global::MelandGame3.TaskOption> _repeated_options_codec
        = pb::FieldCodec.ForMessage(34, global::MelandGame3.TaskOption.Parser);
    private readonly pbc::RepeatedField<global::MelandGame3.TaskOption> options_ = new pbc::RepeatedField<global::MelandGame3.TaskOption>();
    /// <summary>
    /// 子项信息
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::MelandGame3.TaskOption> Options {
      get { return options_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Task);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Task other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TaskId != other.TaskId) return false;
      if (TaskKind != other.TaskKind) return false;
      if (CreatedAtSec != other.CreatedAtSec) return false;
      if(!options_.Equals(other.options_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (TaskId != 0) hash ^= TaskId.GetHashCode();
      if (TaskKind != global::MelandGame3.TaskType.TaskTypeUnknown) hash ^= TaskKind.GetHashCode();
      if (CreatedAtSec != 0L) hash ^= CreatedAtSec.GetHashCode();
      hash ^= options_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (TaskId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(TaskId);
      }
      if (TaskKind != global::MelandGame3.TaskType.TaskTypeUnknown) {
        output.WriteRawTag(16);
        output.WriteEnum((int) TaskKind);
      }
      if (CreatedAtSec != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(CreatedAtSec);
      }
      options_.WriteTo(output, _repeated_options_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (TaskId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(TaskId);
      }
      if (TaskKind != global::MelandGame3.TaskType.TaskTypeUnknown) {
        output.WriteRawTag(16);
        output.WriteEnum((int) TaskKind);
      }
      if (CreatedAtSec != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(CreatedAtSec);
      }
      options_.WriteTo(ref output, _repeated_options_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (TaskId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TaskId);
      }
      if (TaskKind != global::MelandGame3.TaskType.TaskTypeUnknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) TaskKind);
      }
      if (CreatedAtSec != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(CreatedAtSec);
      }
      size += options_.CalculateSize(_repeated_options_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Task other) {
      if (other == null) {
        return;
      }
      if (other.TaskId != 0) {
        TaskId = other.TaskId;
      }
      if (other.TaskKind != global::MelandGame3.TaskType.TaskTypeUnknown) {
        TaskKind = other.TaskKind;
      }
      if (other.CreatedAtSec != 0L) {
        CreatedAtSec = other.CreatedAtSec;
      }
      options_.Add(other.options_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            TaskId = input.ReadInt32();
            break;
          }
          case 16: {
            TaskKind = (global::MelandGame3.TaskType) input.ReadEnum();
            break;
          }
          case 24: {
            CreatedAtSec = input.ReadInt64();
            break;
          }
          case 34: {
            options_.AddEntriesFrom(input, _repeated_options_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            TaskId = input.ReadInt32();
            break;
          }
          case 16: {
            TaskKind = (global::MelandGame3.TaskType) input.ReadEnum();
            break;
          }
          case 24: {
            CreatedAtSec = input.ReadInt64();
            break;
          }
          case 34: {
            options_.AddEntriesFrom(ref input, _repeated_options_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class TaskList : pb::IMessage<TaskList>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TaskList> _parser = new pb::MessageParser<TaskList>(() => new TaskList());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TaskList> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MelandGame3.TaskReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TaskList() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TaskList(TaskList other) : this() {
      id_ = other.id_;
      kind_ = other.kind_;
      canReceive_ = other.canReceive_;
      doing_ = other.doing_;
      rate_ = other.rate_;
      curTask_ = other.curTask_ != null ? other.curTask_.Clone() : null;
      receiveReward_ = other.receiveReward_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TaskList Clone() {
      return new TaskList(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    /// <summary>
    /// task list id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "kind" field.</summary>
    public const int KindFieldNumber = 2;
    private global::MelandGame3.TaskListType kind_ = global::MelandGame3.TaskListType.TaskListTypeUnknown;
    /// <summary>
    /// task list type
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::MelandGame3.TaskListType Kind {
      get { return kind_; }
      set {
        kind_ = value;
      }
    }

    /// <summary>Field number for the "can_receive" field.</summary>
    public const int CanReceiveFieldNumber = 3;
    private bool canReceive_;
    /// <summary>
    /// 任务链是否可以在接取
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool CanReceive {
      get { return canReceive_; }
      set {
        canReceive_ = value;
      }
    }

    /// <summary>Field number for the "doing" field.</summary>
    public const int DoingFieldNumber = 4;
    private bool doing_;
    /// <summary>
    /// 任务链是否正在进行
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Doing {
      get { return doing_; }
      set {
        doing_ = value;
      }
    }

    /// <summary>Field number for the "rate" field.</summary>
    public const int RateFieldNumber = 5;
    private int rate_;
    /// <summary>
    /// 进度
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Rate {
      get { return rate_; }
      set {
        rate_ = value;
      }
    }

    /// <summary>Field number for the "cur_task" field.</summary>
    public const int CurTaskFieldNumber = 6;
    private global::MelandGame3.Task curTask_;
    /// <summary>
    /// current task
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::MelandGame3.Task CurTask {
      get { return curTask_; }
      set {
        curTask_ = value;
      }
    }

    /// <summary>Field number for the "receive_reward" field.</summary>
    public const int ReceiveRewardFieldNumber = 7;
    private int receiveReward_;
    /// <summary>
    /// 任务奖励的领取进度(0, 1, 2)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ReceiveReward {
      get { return receiveReward_; }
      set {
        receiveReward_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TaskList);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TaskList other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Kind != other.Kind) return false;
      if (CanReceive != other.CanReceive) return false;
      if (Doing != other.Doing) return false;
      if (Rate != other.Rate) return false;
      if (!object.Equals(CurTask, other.CurTask)) return false;
      if (ReceiveReward != other.ReceiveReward) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (Kind != global::MelandGame3.TaskListType.TaskListTypeUnknown) hash ^= Kind.GetHashCode();
      if (CanReceive != false) hash ^= CanReceive.GetHashCode();
      if (Doing != false) hash ^= Doing.GetHashCode();
      if (Rate != 0) hash ^= Rate.GetHashCode();
      if (curTask_ != null) hash ^= CurTask.GetHashCode();
      if (ReceiveReward != 0) hash ^= ReceiveReward.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Kind != global::MelandGame3.TaskListType.TaskListTypeUnknown) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Kind);
      }
      if (CanReceive != false) {
        output.WriteRawTag(24);
        output.WriteBool(CanReceive);
      }
      if (Doing != false) {
        output.WriteRawTag(32);
        output.WriteBool(Doing);
      }
      if (Rate != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Rate);
      }
      if (curTask_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(CurTask);
      }
      if (ReceiveReward != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(ReceiveReward);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Kind != global::MelandGame3.TaskListType.TaskListTypeUnknown) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Kind);
      }
      if (CanReceive != false) {
        output.WriteRawTag(24);
        output.WriteBool(CanReceive);
      }
      if (Doing != false) {
        output.WriteRawTag(32);
        output.WriteBool(Doing);
      }
      if (Rate != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Rate);
      }
      if (curTask_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(CurTask);
      }
      if (ReceiveReward != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(ReceiveReward);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (Kind != global::MelandGame3.TaskListType.TaskListTypeUnknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Kind);
      }
      if (CanReceive != false) {
        size += 1 + 1;
      }
      if (Doing != false) {
        size += 1 + 1;
      }
      if (Rate != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Rate);
      }
      if (curTask_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CurTask);
      }
      if (ReceiveReward != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ReceiveReward);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TaskList other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.Kind != global::MelandGame3.TaskListType.TaskListTypeUnknown) {
        Kind = other.Kind;
      }
      if (other.CanReceive != false) {
        CanReceive = other.CanReceive;
      }
      if (other.Doing != false) {
        Doing = other.Doing;
      }
      if (other.Rate != 0) {
        Rate = other.Rate;
      }
      if (other.curTask_ != null) {
        if (curTask_ == null) {
          CurTask = new global::MelandGame3.Task();
        }
        CurTask.MergeFrom(other.CurTask);
      }
      if (other.ReceiveReward != 0) {
        ReceiveReward = other.ReceiveReward;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 16: {
            Kind = (global::MelandGame3.TaskListType) input.ReadEnum();
            break;
          }
          case 24: {
            CanReceive = input.ReadBool();
            break;
          }
          case 32: {
            Doing = input.ReadBool();
            break;
          }
          case 40: {
            Rate = input.ReadInt32();
            break;
          }
          case 50: {
            if (curTask_ == null) {
              CurTask = new global::MelandGame3.Task();
            }
            input.ReadMessage(CurTask);
            break;
          }
          case 56: {
            ReceiveReward = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 16: {
            Kind = (global::MelandGame3.TaskListType) input.ReadEnum();
            break;
          }
          case 24: {
            CanReceive = input.ReadBool();
            break;
          }
          case 32: {
            Doing = input.ReadBool();
            break;
          }
          case 40: {
            Rate = input.ReadInt32();
            break;
          }
          case 50: {
            if (curTask_ == null) {
              CurTask = new global::MelandGame3.Task();
            }
            input.ReadMessage(CurTask);
            break;
          }
          case 56: {
            ReceiveReward = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// 用户已接任务列表
  /// </summary>
  public sealed partial class PlayerTask : pb::IMessage<PlayerTask>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PlayerTask> _parser = new pb::MessageParser<PlayerTask>(() => new PlayerTask());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PlayerTask> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MelandGame3.TaskReflection.Descriptor.MessageTypes[8]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerTask() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerTask(PlayerTask other) : this() {
      taskLists_ = other.taskLists_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerTask Clone() {
      return new PlayerTask(this);
    }

    /// <summary>Field number for the "task_lists" field.</summary>
    public const int TaskListsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::MelandGame3.TaskList> _repeated_taskLists_codec
        = pb::FieldCodec.ForMessage(10, global::MelandGame3.TaskList.Parser);
    private readonly pbc::RepeatedField<global::MelandGame3.TaskList> taskLists_ = new pbc::RepeatedField<global::MelandGame3.TaskList>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::MelandGame3.TaskList> TaskLists {
      get { return taskLists_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PlayerTask);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PlayerTask other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!taskLists_.Equals(other.taskLists_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= taskLists_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      taskLists_.WriteTo(output, _repeated_taskLists_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      taskLists_.WriteTo(ref output, _repeated_taskLists_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += taskLists_.CalculateSize(_repeated_taskLists_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PlayerTask other) {
      if (other == null) {
        return;
      }
      taskLists_.Add(other.taskLists_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            taskLists_.AddEntriesFrom(input, _repeated_taskLists_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            taskLists_.AddEntriesFrom(ref input, _repeated_taskLists_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
